// AUTOMATICALLY GENERATED by FreeHEP JAVAGraphics2D

package org.freehep.graphicsio.java.test;

import java.awt.*;
import java.awt.geom.*;
import java.awt.image.*;
import javax.swing.*;
import org.freehep.graphics2d.*;
import org.freehep.graphicsio.java.*;
import org.freehep.graphicsio.test.*;

public class TestClip extends TestingPanel {

    public TestClip(String[] args) throws Exception {
        super(args);
        setName("TestClip");
    } // contructor

    public void paint(Graphics g) {
        vg[0] = VectorGraphics.create(g);
        vg[0].setCreator("FreeHEP JAVAGraphics2D");
        Paint0s0.paint(vg);
    } // paint

    private static class Paint0s0 {
        public static void paint(VectorGraphics[] vg) {
            vg[0].setColor(new Color(0, 0, 0, 255));
            vg[0].setFont(new Font("Dialog", 0, 12));
            vg[1] = (VectorGraphics)vg[0].create();
            vg[1].setClip(0, 0, 600, 600);
            vg[1].setColor(new Color(192, 192, 192, 255));
            vg[1].fillRect(0, 0, 600, 600);
            vg[1].setColor(new Color(0, 0, 0, 255));
            vg[2] = (VectorGraphics)vg[1].create();
            vg[2].drawString("NoClip", 10, 20);
            vg[2].scale(8.0, 8.0);
            vg[2].translate(1.25, 1.25);
            vg[2].translate(10.625, 0.0);
            vg[2].setColor(new Color(255, 0, 0, 255));
            vg[2].setLineWidth(0.125);
            vg[2].draw(new JAVAGeneralPath(1, new JAVAGeneralPath.PathElement[] {
                new JAVAGeneralPath.MoveTo(1.0f, 1.0f),
                new JAVAGeneralPath.LineTo(7.0f, 1.0f),
                new JAVAGeneralPath.LineTo(7.0f, 3.0f),
                new JAVAGeneralPath.LineTo(1.0f, 3.0f),
                new JAVAGeneralPath.LineTo(1.0f, 1.0f),
                new JAVAGeneralPath.ClosePath()
            }));
            vg[2].setColor(new Color(0, 0, 0, 255));
            vg[2].setLineWidth(0.375);
            vg[2].draw(new JAVAGeneralPath(1, new JAVAGeneralPath.PathElement[] {
                new JAVAGeneralPath.MoveTo(0.0f, 2.0f),
                new JAVAGeneralPath.LineTo(2.0f, 2.0f),
                new JAVAGeneralPath.LineTo(3.0f, 1.0f),
                new JAVAGeneralPath.LineTo(4.0f, 1.0f),
                new JAVAGeneralPath.LineTo(5.0f, 0.0f),
                new JAVAGeneralPath.LineTo(6.0f, 2.0f),
                new JAVAGeneralPath.LineTo(8.0f, 2.0f),
                new JAVAGeneralPath.LineTo(8.0f, 0.0f),
                new JAVAGeneralPath.LineTo(0.0f, 0.0f),
                new JAVAGeneralPath.ClosePath()
            }));
            vg[2].translate(10.625, 0.0);
            vg[2].setColor(new Color(255, 0, 0, 255));
            vg[2].setLineWidth(0.125);
            vg[2].draw(new JAVAGeneralPath(1, new JAVAGeneralPath.PathElement[] {
                new JAVAGeneralPath.MoveTo(1.0f, 1.0f),
                new JAVAGeneralPath.LineTo(1.0f, 3.0f),
                new JAVAGeneralPath.LineTo(7.0f, 3.0f),
                new JAVAGeneralPath.LineTo(7.0f, 1.0f),
                new JAVAGeneralPath.LineTo(5.0f, 1.0f),
                new JAVAGeneralPath.LineTo(4.0f, 3.0f),
                new JAVAGeneralPath.LineTo(3.0f, 1.0f),
                new JAVAGeneralPath.ClosePath()
            }));
            vg[2].setColor(new Color(0, 0, 0, 255));
            vg[2].setLineWidth(0.375);
            vg[2].draw(new JAVAGeneralPath(1, new JAVAGeneralPath.PathElement[] {
                new JAVAGeneralPath.MoveTo(0.0f, 0.0f),
                new JAVAGeneralPath.LineTo(8.0f, 0.0f),
                new JAVAGeneralPath.LineTo(8.0f, 2.0f),
                new JAVAGeneralPath.LineTo(0.0f, 2.0f),
                new JAVAGeneralPath.LineTo(0.0f, 0.0f),
                new JAVAGeneralPath.ClosePath()
            }));
            vg[2].translate(10.625, 0.0);
            vg[2].setColor(new Color(255, 0, 0, 255));
            vg[2].setLineWidth(0.125);
            vg[2].draw(new JAVAGeneralPath(1, new JAVAGeneralPath.PathElement[] {
                new JAVAGeneralPath.MoveTo(1.0f, 1.0f),
                new JAVAGeneralPath.LineTo(7.0f, 1.0f),
                new JAVAGeneralPath.LineTo(7.0f, 3.0f),
                new JAVAGeneralPath.LineTo(1.0f, 3.0f),
                new JAVAGeneralPath.LineTo(1.0f, 1.0f),
                new JAVAGeneralPath.ClosePath()
            }));
            vg[2].setColor(new Color(0, 0, 0, 255));
            vg[2].setLineWidth(0.375);
            vg[2].draw(new JAVAGeneralPath(1, new JAVAGeneralPath.PathElement[] {
                new JAVAGeneralPath.MoveTo(0.0f, 2.0f),
                new JAVAGeneralPath.LineTo(2.0f, 2.0f),
                new JAVAGeneralPath.LineTo(3.0f, 1.0f),
                new JAVAGeneralPath.LineTo(5.0f, 1.0f),
                new JAVAGeneralPath.LineTo(6.0f, 2.0f),
                new JAVAGeneralPath.LineTo(8.0f, 2.0f),
                new JAVAGeneralPath.LineTo(8.0f, 0.0f),
                new JAVAGeneralPath.LineTo(0.0f, 0.0f),
                new JAVAGeneralPath.ClosePath()
            }));
            vg[2].translate(10.625, 0.0);
            vg[2].setColor(new Color(255, 0, 0, 255));
            vg[2].setLineWidth(0.125);
            vg[2].draw(new JAVAGeneralPath(1, new JAVAGeneralPath.PathElement[] {
                new JAVAGeneralPath.MoveTo(1.0f, 1.0f),
                new JAVAGeneralPath.LineTo(7.0f, 1.0f),
                new JAVAGeneralPath.LineTo(7.0f, 3.0f),
                new JAVAGeneralPath.LineTo(1.0f, 3.0f),
                new JAVAGeneralPath.LineTo(1.0f, 1.0f),
                new JAVAGeneralPath.ClosePath()
            }));
            vg[2].setColor(new Color(0, 0, 0, 255));
            vg[2].setLineWidth(0.375);
            vg[2].draw(new JAVAGeneralPath(1, new JAVAGeneralPath.PathElement[] {
                new JAVAGeneralPath.MoveTo(6.0f, 2.0f),
                new JAVAGeneralPath.CurveTo(6.0f, 3.1045694f, 5.1045694f, 4.0f, 4.0f, 4.0f),
                new JAVAGeneralPath.CurveTo(2.8954306f, 4.0f, 2.0f, 3.1045694f, 2.0f, 2.0f),
                new JAVAGeneralPath.CurveTo(2.0f, 0.8954305f, 2.8954306f, 0.0f, 4.0f, 0.0f),
                new JAVAGeneralPath.CurveTo(5.1045694f, 0.0f, 6.0f, 0.8954305f, 6.0f, 2.0f),
                new JAVAGeneralPath.ClosePath()
            }));
            vg[2].translate(10.625, 0.0);
            vg[2].setColor(new Color(255, 0, 0, 255));
            vg[2].setLineWidth(0.125);
            vg[2].draw(new JAVAGeneralPath(1, new JAVAGeneralPath.PathElement[] {
                new JAVAGeneralPath.MoveTo(1.0f, 1.0f),
                new JAVAGeneralPath.LineTo(7.0f, 1.0f),
                new JAVAGeneralPath.LineTo(7.0f, 3.0f),
                new JAVAGeneralPath.LineTo(1.0f, 3.0f),
                new JAVAGeneralPath.LineTo(1.0f, 1.0f),
                new JAVAGeneralPath.ClosePath()
            }));
            vg[2].setColor(new Color(0, 0, 0, 255));
            vg[2].setLineWidth(0.375);
            vg[2].draw(new JAVAGeneralPath(1, new JAVAGeneralPath.PathElement[] {
                new JAVAGeneralPath.MoveTo(0.0f, 2.0f),
                new JAVAGeneralPath.LineTo(3.0f, 2.0f),
                new JAVAGeneralPath.LineTo(4.0f, 1.0f),
                new JAVAGeneralPath.LineTo(5.0f, 2.0f),
                new JAVAGeneralPath.LineTo(8.0f, 2.0f),
                new JAVAGeneralPath.LineTo(8.0f, 0.0f),
                new JAVAGeneralPath.LineTo(0.0f, 0.0f),
                new JAVAGeneralPath.ClosePath()
            }));
            vg[2].translate(10.625, 0.0);
            vg[2].setColor(new Color(255, 0, 0, 255));
            vg[2].setLineWidth(0.125);
            vg[2].draw(new JAVAGeneralPath(1, new JAVAGeneralPath.PathElement[] {
                new JAVAGeneralPath.MoveTo(7.0f, 2.0f),
                new JAVAGeneralPath.CurveTo(7.0f, 2.5522847f, 5.656854f, 3.0f, 4.0f, 3.0f),
                new JAVAGeneralPath.CurveTo(2.3431458f, 3.0f, 1.0f, 2.5522847f, 1.0f, 2.0f),
                new JAVAGeneralPath.CurveTo(1.0f, 1.4477153f, 2.3431458f, 1.0f, 4.0f, 1.0f),
                new JAVAGeneralPath.CurveTo(5.656854f, 1.0f, 7.0f, 1.4477153f, 7.0f, 2.0f),
                new JAVAGeneralPath.ClosePath()
            }));
            vg[2].setColor(new Color(0, 0, 0, 255));
            vg[2].setLineWidth(0.375);
            vg[2].draw(new JAVAGeneralPath(1, new JAVAGeneralPath.PathElement[] {
                new JAVAGeneralPath.MoveTo(6.0f, 2.0f),
                new JAVAGeneralPath.CurveTo(6.0f, 3.1045694f, 5.1045694f, 4.0f, 4.0f, 4.0f),
                new JAVAGeneralPath.CurveTo(2.8954306f, 4.0f, 2.0f, 3.1045694f, 2.0f, 2.0f),
                new JAVAGeneralPath.CurveTo(2.0f, 0.8954305f, 2.8954306f, 0.0f, 4.0f, 0.0f),
                new JAVAGeneralPath.CurveTo(5.1045694f, 0.0f, 6.0f, 0.8954305f, 6.0f, 2.0f),
                new JAVAGeneralPath.ClosePath()
            }));
            vg[2].dispose();
            vg[3] = (VectorGraphics)vg[1].create();
            vg[3].drawString("JavaClip", 10, 120);
            vg[3].scale(8.0, 8.0);
            vg[3].translate(1.25, 13.75);
            vg[3].translate(10.625, 0.0);
            vg[4] = (VectorGraphics)vg[3].create();
            vg[4].setColor(new Color(255, 0, 0, 255));
            vg[4].setLineWidth(0.125);
            vg[4].draw(new JAVAGeneralPath(1, new JAVAGeneralPath.PathElement[] {
                new JAVAGeneralPath.MoveTo(1.0f, 1.0f),
                new JAVAGeneralPath.LineTo(7.0f, 1.0f),
                new JAVAGeneralPath.LineTo(7.0f, 3.0f),
                new JAVAGeneralPath.LineTo(1.0f, 3.0f),
                new JAVAGeneralPath.LineTo(1.0f, 1.0f),
                new JAVAGeneralPath.ClosePath()
            }));
            vg[4].clip(new JAVAGeneralPath(1, new JAVAGeneralPath.PathElement[] {
                new JAVAGeneralPath.MoveTo(1.0f, 1.0f),
                new JAVAGeneralPath.LineTo(7.0f, 1.0f),
                new JAVAGeneralPath.LineTo(7.0f, 3.0f),
                new JAVAGeneralPath.LineTo(1.0f, 3.0f),
                new JAVAGeneralPath.LineTo(1.0f, 1.0f),
                new JAVAGeneralPath.ClosePath()
            }));
            Paint0s1.paint(vg);
        } // paint
    } // class Paint0s0

    private static class Paint0s1 {
        public static void paint(VectorGraphics[] vg) {
            vg[4].setColor(new Color(0, 0, 0, 255));
            vg[4].setLineWidth(0.375);
            vg[4].draw(new JAVAGeneralPath(1, new JAVAGeneralPath.PathElement[] {
                new JAVAGeneralPath.MoveTo(0.0f, 2.0f),
                new JAVAGeneralPath.LineTo(2.0f, 2.0f),
                new JAVAGeneralPath.LineTo(3.0f, 1.0f),
                new JAVAGeneralPath.LineTo(4.0f, 1.0f),
                new JAVAGeneralPath.LineTo(5.0f, 0.0f),
                new JAVAGeneralPath.LineTo(6.0f, 2.0f),
                new JAVAGeneralPath.LineTo(8.0f, 2.0f),
                new JAVAGeneralPath.LineTo(8.0f, 0.0f),
                new JAVAGeneralPath.LineTo(0.0f, 0.0f),
                new JAVAGeneralPath.ClosePath()
            }));
            vg[4].dispose();
            vg[3].translate(10.625, 0.0);
            vg[5] = (VectorGraphics)vg[3].create();
            vg[5].setColor(new Color(255, 0, 0, 255));
            vg[5].setLineWidth(0.125);
            vg[5].draw(new JAVAGeneralPath(1, new JAVAGeneralPath.PathElement[] {
                new JAVAGeneralPath.MoveTo(1.0f, 1.0f),
                new JAVAGeneralPath.LineTo(1.0f, 3.0f),
                new JAVAGeneralPath.LineTo(7.0f, 3.0f),
                new JAVAGeneralPath.LineTo(7.0f, 1.0f),
                new JAVAGeneralPath.LineTo(5.0f, 1.0f),
                new JAVAGeneralPath.LineTo(4.0f, 3.0f),
                new JAVAGeneralPath.LineTo(3.0f, 1.0f),
                new JAVAGeneralPath.ClosePath()
            }));
            vg[5].clip(new JAVAGeneralPath(1, new JAVAGeneralPath.PathElement[] {
                new JAVAGeneralPath.MoveTo(1.0f, 1.0f),
                new JAVAGeneralPath.LineTo(1.0f, 3.0f),
                new JAVAGeneralPath.LineTo(7.0f, 3.0f),
                new JAVAGeneralPath.LineTo(7.0f, 1.0f),
                new JAVAGeneralPath.LineTo(5.0f, 1.0f),
                new JAVAGeneralPath.LineTo(4.0f, 3.0f),
                new JAVAGeneralPath.LineTo(3.0f, 1.0f),
                new JAVAGeneralPath.ClosePath()
            }));
            vg[5].setColor(new Color(0, 0, 0, 255));
            vg[5].setLineWidth(0.375);
            vg[5].draw(new JAVAGeneralPath(1, new JAVAGeneralPath.PathElement[] {
                new JAVAGeneralPath.MoveTo(0.0f, 0.0f),
                new JAVAGeneralPath.LineTo(8.0f, 0.0f),
                new JAVAGeneralPath.LineTo(8.0f, 2.0f),
                new JAVAGeneralPath.LineTo(0.0f, 2.0f),
                new JAVAGeneralPath.LineTo(0.0f, 0.0f),
                new JAVAGeneralPath.ClosePath()
            }));
            vg[5].dispose();
            vg[3].translate(10.625, 0.0);
            vg[6] = (VectorGraphics)vg[3].create();
            vg[6].setColor(new Color(255, 0, 0, 255));
            vg[6].setLineWidth(0.125);
            vg[6].draw(new JAVAGeneralPath(1, new JAVAGeneralPath.PathElement[] {
                new JAVAGeneralPath.MoveTo(1.0f, 1.0f),
                new JAVAGeneralPath.LineTo(7.0f, 1.0f),
                new JAVAGeneralPath.LineTo(7.0f, 3.0f),
                new JAVAGeneralPath.LineTo(1.0f, 3.0f),
                new JAVAGeneralPath.LineTo(1.0f, 1.0f),
                new JAVAGeneralPath.ClosePath()
            }));
            vg[6].clip(new JAVAGeneralPath(1, new JAVAGeneralPath.PathElement[] {
                new JAVAGeneralPath.MoveTo(1.0f, 1.0f),
                new JAVAGeneralPath.LineTo(7.0f, 1.0f),
                new JAVAGeneralPath.LineTo(7.0f, 3.0f),
                new JAVAGeneralPath.LineTo(1.0f, 3.0f),
                new JAVAGeneralPath.LineTo(1.0f, 1.0f),
                new JAVAGeneralPath.ClosePath()
            }));
            vg[6].setColor(new Color(0, 0, 0, 255));
            vg[6].setLineWidth(0.375);
            vg[6].draw(new JAVAGeneralPath(1, new JAVAGeneralPath.PathElement[] {
                new JAVAGeneralPath.MoveTo(0.0f, 2.0f),
                new JAVAGeneralPath.LineTo(2.0f, 2.0f),
                new JAVAGeneralPath.LineTo(3.0f, 1.0f),
                new JAVAGeneralPath.LineTo(5.0f, 1.0f),
                new JAVAGeneralPath.LineTo(6.0f, 2.0f),
                new JAVAGeneralPath.LineTo(8.0f, 2.0f),
                new JAVAGeneralPath.LineTo(8.0f, 0.0f),
                new JAVAGeneralPath.LineTo(0.0f, 0.0f),
                new JAVAGeneralPath.ClosePath()
            }));
            vg[6].dispose();
            vg[3].translate(10.625, 0.0);
            vg[7] = (VectorGraphics)vg[3].create();
            vg[7].setColor(new Color(255, 0, 0, 255));
            vg[7].setLineWidth(0.125);
            vg[7].draw(new JAVAGeneralPath(1, new JAVAGeneralPath.PathElement[] {
                new JAVAGeneralPath.MoveTo(1.0f, 1.0f),
                new JAVAGeneralPath.LineTo(7.0f, 1.0f),
                new JAVAGeneralPath.LineTo(7.0f, 3.0f),
                new JAVAGeneralPath.LineTo(1.0f, 3.0f),
                new JAVAGeneralPath.LineTo(1.0f, 1.0f),
                new JAVAGeneralPath.ClosePath()
            }));
            vg[7].clip(new JAVAGeneralPath(1, new JAVAGeneralPath.PathElement[] {
                new JAVAGeneralPath.MoveTo(1.0f, 1.0f),
                new JAVAGeneralPath.LineTo(7.0f, 1.0f),
                new JAVAGeneralPath.LineTo(7.0f, 3.0f),
                new JAVAGeneralPath.LineTo(1.0f, 3.0f),
                new JAVAGeneralPath.LineTo(1.0f, 1.0f),
                new JAVAGeneralPath.ClosePath()
            }));
            vg[7].setColor(new Color(0, 0, 0, 255));
            vg[7].setLineWidth(0.375);
            vg[7].draw(new JAVAGeneralPath(1, new JAVAGeneralPath.PathElement[] {
                new JAVAGeneralPath.MoveTo(6.0f, 2.0f),
                new JAVAGeneralPath.CurveTo(6.0f, 3.1045694f, 5.1045694f, 4.0f, 4.0f, 4.0f),
                new JAVAGeneralPath.CurveTo(2.8954306f, 4.0f, 2.0f, 3.1045694f, 2.0f, 2.0f),
                new JAVAGeneralPath.CurveTo(2.0f, 0.8954305f, 2.8954306f, 0.0f, 4.0f, 0.0f),
                new JAVAGeneralPath.CurveTo(5.1045694f, 0.0f, 6.0f, 0.8954305f, 6.0f, 2.0f),
                new JAVAGeneralPath.ClosePath()
            }));
            vg[7].dispose();
            vg[3].translate(10.625, 0.0);
            vg[8] = (VectorGraphics)vg[3].create();
            vg[8].setColor(new Color(255, 0, 0, 255));
            vg[8].setLineWidth(0.125);
            vg[8].draw(new JAVAGeneralPath(1, new JAVAGeneralPath.PathElement[] {
                new JAVAGeneralPath.MoveTo(1.0f, 1.0f),
                new JAVAGeneralPath.LineTo(7.0f, 1.0f),
                new JAVAGeneralPath.LineTo(7.0f, 3.0f),
                new JAVAGeneralPath.LineTo(1.0f, 3.0f),
                new JAVAGeneralPath.LineTo(1.0f, 1.0f),
                new JAVAGeneralPath.ClosePath()
            }));
            vg[8].clip(new JAVAGeneralPath(1, new JAVAGeneralPath.PathElement[] {
                new JAVAGeneralPath.MoveTo(1.0f, 1.0f),
                new JAVAGeneralPath.LineTo(7.0f, 1.0f),
                new JAVAGeneralPath.LineTo(7.0f, 3.0f),
                new JAVAGeneralPath.LineTo(1.0f, 3.0f),
                new JAVAGeneralPath.LineTo(1.0f, 1.0f),
                new JAVAGeneralPath.ClosePath()
            }));
            vg[8].setColor(new Color(0, 0, 0, 255));
            vg[8].setLineWidth(0.375);
            vg[8].draw(new JAVAGeneralPath(1, new JAVAGeneralPath.PathElement[] {
                new JAVAGeneralPath.MoveTo(0.0f, 2.0f),
                new JAVAGeneralPath.LineTo(3.0f, 2.0f),
                new JAVAGeneralPath.LineTo(4.0f, 1.0f),
                new JAVAGeneralPath.LineTo(5.0f, 2.0f),
                new JAVAGeneralPath.LineTo(8.0f, 2.0f),
                new JAVAGeneralPath.LineTo(8.0f, 0.0f),
                new JAVAGeneralPath.LineTo(0.0f, 0.0f),
                new JAVAGeneralPath.ClosePath()
            }));
            vg[8].dispose();
            vg[3].translate(10.625, 0.0);
            vg[9] = (VectorGraphics)vg[3].create();
            vg[9].setColor(new Color(255, 0, 0, 255));
            vg[9].setLineWidth(0.125);
            vg[9].draw(new JAVAGeneralPath(1, new JAVAGeneralPath.PathElement[] {
                new JAVAGeneralPath.MoveTo(7.0f, 2.0f),
                new JAVAGeneralPath.CurveTo(7.0f, 2.5522847f, 5.656854f, 3.0f, 4.0f, 3.0f),
                new JAVAGeneralPath.CurveTo(2.3431458f, 3.0f, 1.0f, 2.5522847f, 1.0f, 2.0f),
                new JAVAGeneralPath.CurveTo(1.0f, 1.4477153f, 2.3431458f, 1.0f, 4.0f, 1.0f),
                new JAVAGeneralPath.CurveTo(5.656854f, 1.0f, 7.0f, 1.4477153f, 7.0f, 2.0f),
                new JAVAGeneralPath.ClosePath()
            }));
            vg[9].clip(new JAVAGeneralPath(1, new JAVAGeneralPath.PathElement[] {
                new JAVAGeneralPath.MoveTo(7.0f, 2.0f),
                new JAVAGeneralPath.CurveTo(7.0f, 2.5522847f, 5.656854f, 3.0f, 4.0f, 3.0f),
                new JAVAGeneralPath.CurveTo(2.3431458f, 3.0f, 1.0f, 2.5522847f, 1.0f, 2.0f),
                new JAVAGeneralPath.CurveTo(1.0f, 1.4477153f, 2.3431458f, 1.0f, 4.0f, 1.0f),
                new JAVAGeneralPath.CurveTo(5.656854f, 1.0f, 7.0f, 1.4477153f, 7.0f, 2.0f),
                new JAVAGeneralPath.ClosePath()
            }));
            vg[9].setColor(new Color(0, 0, 0, 255));
            vg[9].setLineWidth(0.375);
            vg[9].draw(new JAVAGeneralPath(1, new JAVAGeneralPath.PathElement[] {
                new JAVAGeneralPath.MoveTo(6.0f, 2.0f),
                new JAVAGeneralPath.CurveTo(6.0f, 3.1045694f, 5.1045694f, 4.0f, 4.0f, 4.0f),
                new JAVAGeneralPath.CurveTo(2.8954306f, 4.0f, 2.0f, 3.1045694f, 2.0f, 2.0f),
                new JAVAGeneralPath.CurveTo(2.0f, 0.8954305f, 2.8954306f, 0.0f, 4.0f, 0.0f),
                new JAVAGeneralPath.CurveTo(5.1045694f, 0.0f, 6.0f, 0.8954305f, 6.0f, 2.0f),
                new JAVAGeneralPath.ClosePath()
            }));
            vg[9].dispose();
            vg[3].dispose();
            vg[10] = (VectorGraphics)vg[1].create();
            vg[10].drawString("OurClip", 10, 220);
            vg[10].scale(8.0, 8.0);
            vg[10].translate(1.25, 26.25);
            vg[10].translate(10.625, 0.0);
            vg[11] = (VectorGraphics)vg[10].create();
            vg[11].setColor(new Color(255, 0, 0, 255));
            vg[11].setLineWidth(0.125);
            vg[11].draw(new JAVAGeneralPath(1, new JAVAGeneralPath.PathElement[] {
                new JAVAGeneralPath.MoveTo(1.0f, 1.0f),
                new JAVAGeneralPath.LineTo(7.0f, 1.0f),
                new JAVAGeneralPath.LineTo(7.0f, 3.0f),
                new JAVAGeneralPath.LineTo(1.0f, 3.0f),
                new JAVAGeneralPath.LineTo(1.0f, 1.0f),
                new JAVAGeneralPath.ClosePath()
            }));
            Paint0s2.paint(vg);
        } // paint
    } // class Paint0s1

    private static class Paint0s2 {
        public static void paint(VectorGraphics[] vg) {
            vg[11].setColor(new Color(0, 0, 0, 255));
            vg[11].setLineWidth(0.375);
            vg[11].draw(new JAVAGeneralPath(1, new JAVAGeneralPath.PathElement[] {
                new JAVAGeneralPath.MoveTo(1.0f, 1.0f),
                new JAVAGeneralPath.LineTo(1.0f, 2.0f),
                new JAVAGeneralPath.LineTo(2.0f, 2.0f),
                new JAVAGeneralPath.LineTo(3.0f, 1.0f),
                new JAVAGeneralPath.ClosePath(),
                new JAVAGeneralPath.MoveTo(5.5f, 1.0f),
                new JAVAGeneralPath.LineTo(6.0f, 2.0f),
                new JAVAGeneralPath.LineTo(7.0f, 2.0f),
                new JAVAGeneralPath.LineTo(7.0f, 1.0f),
                new JAVAGeneralPath.ClosePath()
            }));
            vg[11].dispose();
            vg[10].translate(10.625, 0.0);
            vg[12] = (VectorGraphics)vg[10].create();
            vg[12].setColor(new Color(255, 0, 0, 255));
            vg[12].setLineWidth(0.125);
            vg[12].draw(new JAVAGeneralPath(1, new JAVAGeneralPath.PathElement[] {
                new JAVAGeneralPath.MoveTo(1.0f, 1.0f),
                new JAVAGeneralPath.LineTo(1.0f, 3.0f),
                new JAVAGeneralPath.LineTo(7.0f, 3.0f),
                new JAVAGeneralPath.LineTo(7.0f, 1.0f),
                new JAVAGeneralPath.LineTo(5.0f, 1.0f),
                new JAVAGeneralPath.LineTo(4.0f, 3.0f),
                new JAVAGeneralPath.LineTo(3.0f, 1.0f),
                new JAVAGeneralPath.ClosePath()
            }));
            vg[12].setColor(new Color(0, 0, 0, 255));
            vg[12].setLineWidth(0.375);
            vg[12].draw(new JAVAGeneralPath(1, new JAVAGeneralPath.PathElement[] {
                new JAVAGeneralPath.MoveTo(1.0f, 1.0f),
                new JAVAGeneralPath.LineTo(1.0f, 2.0f),
                new JAVAGeneralPath.LineTo(3.5f, 2.0f),
                new JAVAGeneralPath.LineTo(3.0f, 1.0f),
                new JAVAGeneralPath.ClosePath(),
                new JAVAGeneralPath.MoveTo(5.0f, 1.0f),
                new JAVAGeneralPath.LineTo(4.5f, 2.0f),
                new JAVAGeneralPath.LineTo(7.0f, 2.0f),
                new JAVAGeneralPath.LineTo(7.0f, 1.0f),
                new JAVAGeneralPath.ClosePath()
            }));
            vg[12].dispose();
            vg[10].translate(10.625, 0.0);
            vg[13] = (VectorGraphics)vg[10].create();
            vg[13].setColor(new Color(255, 0, 0, 255));
            vg[13].setLineWidth(0.125);
            vg[13].draw(new JAVAGeneralPath(1, new JAVAGeneralPath.PathElement[] {
                new JAVAGeneralPath.MoveTo(1.0f, 1.0f),
                new JAVAGeneralPath.LineTo(7.0f, 1.0f),
                new JAVAGeneralPath.LineTo(7.0f, 3.0f),
                new JAVAGeneralPath.LineTo(1.0f, 3.0f),
                new JAVAGeneralPath.LineTo(1.0f, 1.0f),
                new JAVAGeneralPath.ClosePath()
            }));
            vg[13].setColor(new Color(0, 0, 0, 255));
            vg[13].setLineWidth(0.375);
            vg[13].draw(new JAVAGeneralPath(1, new JAVAGeneralPath.PathElement[] {
                new JAVAGeneralPath.MoveTo(1.0f, 1.0f),
                new JAVAGeneralPath.LineTo(1.0f, 2.0f),
                new JAVAGeneralPath.LineTo(2.0f, 2.0f),
                new JAVAGeneralPath.LineTo(3.0f, 1.0f),
                new JAVAGeneralPath.ClosePath(),
                new JAVAGeneralPath.MoveTo(5.0f, 1.0f),
                new JAVAGeneralPath.LineTo(6.0f, 2.0f),
                new JAVAGeneralPath.LineTo(7.0f, 2.0f),
                new JAVAGeneralPath.LineTo(7.0f, 1.0f),
                new JAVAGeneralPath.ClosePath()
            }));
            vg[13].dispose();
            vg[10].translate(10.625, 0.0);
            vg[14] = (VectorGraphics)vg[10].create();
            vg[14].setColor(new Color(255, 0, 0, 255));
            vg[14].setLineWidth(0.125);
            vg[14].draw(new JAVAGeneralPath(1, new JAVAGeneralPath.PathElement[] {
                new JAVAGeneralPath.MoveTo(1.0f, 1.0f),
                new JAVAGeneralPath.LineTo(7.0f, 1.0f),
                new JAVAGeneralPath.LineTo(7.0f, 3.0f),
                new JAVAGeneralPath.LineTo(1.0f, 3.0f),
                new JAVAGeneralPath.LineTo(1.0f, 1.0f),
                new JAVAGeneralPath.ClosePath()
            }));
            vg[14].setColor(new Color(0, 0, 0, 255));
            vg[14].setLineWidth(0.375);
            vg[14].draw(new JAVAGeneralPath(1, new JAVAGeneralPath.PathElement[] {
                new JAVAGeneralPath.MoveTo(2.2675643f, 1.0f),
                new JAVAGeneralPath.CurveTo(2.0973942f, 1.2941734f, 2.0f, 1.6357129f, 2.0f, 2.0f),
                new JAVAGeneralPath.CurveTo(2.0f, 2.3642871f, 2.0973942f, 2.7058265f, 2.2675643f, 3.0f),
                new JAVAGeneralPath.LineTo(5.7324357f, 3.0f),
                new JAVAGeneralPath.CurveTo(5.9026055f, 2.7058265f, 6.0f, 2.3642871f, 6.0f, 2.0f),
                new JAVAGeneralPath.CurveTo(6.0f, 1.6357129f, 5.9026055f, 1.2941734f, 5.7324357f, 1.0f),
                new JAVAGeneralPath.ClosePath()
            }));
            vg[14].dispose();
            vg[10].translate(10.625, 0.0);
            vg[15] = (VectorGraphics)vg[10].create();
            vg[15].setColor(new Color(255, 0, 0, 255));
            vg[15].setLineWidth(0.125);
            vg[15].draw(new JAVAGeneralPath(1, new JAVAGeneralPath.PathElement[] {
                new JAVAGeneralPath.MoveTo(1.0f, 1.0f),
                new JAVAGeneralPath.LineTo(7.0f, 1.0f),
                new JAVAGeneralPath.LineTo(7.0f, 3.0f),
                new JAVAGeneralPath.LineTo(1.0f, 3.0f),
                new JAVAGeneralPath.LineTo(1.0f, 1.0f),
                new JAVAGeneralPath.ClosePath()
            }));
            vg[15].setColor(new Color(0, 0, 0, 255));
            vg[15].setLineWidth(0.375);
            vg[15].draw(new JAVAGeneralPath(1, new JAVAGeneralPath.PathElement[] {
                new JAVAGeneralPath.MoveTo(1.0f, 1.0f),
                new JAVAGeneralPath.LineTo(1.0f, 2.0f),
                new JAVAGeneralPath.LineTo(3.0f, 2.0f),
                new JAVAGeneralPath.LineTo(4.0f, 1.0f),
                new JAVAGeneralPath.ClosePath(),
                new JAVAGeneralPath.MoveTo(4.0f, 1.0f),
                new JAVAGeneralPath.LineTo(5.0f, 2.0f),
                new JAVAGeneralPath.LineTo(7.0f, 2.0f),
                new JAVAGeneralPath.LineTo(7.0f, 1.0f),
                new JAVAGeneralPath.ClosePath()
            }));
            vg[15].dispose();
            vg[10].translate(10.625, 0.0);
            vg[16] = (VectorGraphics)vg[10].create();
            vg[16].setColor(new Color(255, 0, 0, 255));
            vg[16].setLineWidth(0.125);
            vg[16].draw(new JAVAGeneralPath(1, new JAVAGeneralPath.PathElement[] {
                new JAVAGeneralPath.MoveTo(7.0f, 2.0f),
                new JAVAGeneralPath.CurveTo(7.0f, 2.5522847f, 5.656854f, 3.0f, 4.0f, 3.0f),
                new JAVAGeneralPath.CurveTo(2.3431458f, 3.0f, 1.0f, 2.5522847f, 1.0f, 2.0f),
                new JAVAGeneralPath.CurveTo(1.0f, 1.4477153f, 2.3431458f, 1.0f, 4.0f, 1.0f),
                new JAVAGeneralPath.CurveTo(5.656854f, 1.0f, 7.0f, 1.4477153f, 7.0f, 2.0f),
                new JAVAGeneralPath.ClosePath()
            }));
            vg[16].setColor(new Color(0, 0, 0, 255));
            vg[16].setLineWidth(0.375);
            vg[16].draw(new JAVAGeneralPath(1, new JAVAGeneralPath.PathElement[] {
                new JAVAGeneralPath.MoveTo(4.0f, 1.0f),
                new JAVAGeneralPath.CurveTo(3.3075979f, 1.0f, 2.6699824f, 1.0781897f, 2.162285f, 1.2095255f),
                new JAVAGeneralPath.LineTo(2.162285f, 1.2095255f),
                new JAVAGeneralPath.CurveTo(2.0578518f, 1.4519914f, 2.0f, 1.7192397f, 2.0f, 2.0f),
                new JAVAGeneralPath.CurveTo(2.0f, 2.2807603f, 2.0578518f, 2.5480087f, 2.1622853f, 2.7904747f),
                new JAVAGeneralPath.LineTo(2.1622853f, 2.7904747f),
                new JAVAGeneralPath.CurveTo(2.6699827f, 2.9218102f, 3.307598f, 3.0f, 4.0f, 3.0f),
                new JAVAGeneralPath.CurveTo(4.692402f, 3.0f, 5.3300176f, 2.9218102f, 5.8377147f, 2.7904744f),
                new JAVAGeneralPath.LineTo(5.8377147f, 2.7904744f),
                new JAVAGeneralPath.CurveTo(5.942148f, 2.5480087f, 6.0f, 2.2807603f, 6.0f, 2.0f),
                new JAVAGeneralPath.CurveTo(6.0f, 1.7192397f, 5.942148f, 1.4519914f, 5.8377147f, 1.2095255f),
                new JAVAGeneralPath.LineTo(5.8377147f, 1.2095255f),
                new JAVAGeneralPath.CurveTo(5.3300176f, 1.0781897f, 4.692402f, 1.0f, 4.0f, 1.0f),
                new JAVAGeneralPath.ClosePath()
            }));
            vg[16].dispose();
            vg[10].dispose();
            vg[17] = (VectorGraphics)vg[1].create();
            vg[17].drawString("NoClip", 10, 320);
            vg[17].scale(8.0, 8.0);
            vg[17].translate(1.25, 38.75);
            vg[17].translate(10.625, 0.0);
            vg[17].setColor(new Color(255, 0, 0, 255));
            vg[17].setLineWidth(0.125);
            vg[17].draw(new JAVAGeneralPath(1, new JAVAGeneralPath.PathElement[] {
                new JAVAGeneralPath.MoveTo(1.0f, 1.0f),
                new JAVAGeneralPath.LineTo(7.0f, 1.0f),
                new JAVAGeneralPath.LineTo(7.0f, 3.0f),
                new JAVAGeneralPath.LineTo(1.0f, 3.0f),
                new JAVAGeneralPath.LineTo(1.0f, 1.0f),
                new JAVAGeneralPath.ClosePath()
            }));
            vg[17].setColor(new Color(0, 0, 0, 255));
            vg[17].setLineWidth(0.375);
            vg[17].fill(new JAVAGeneralPath(1, new JAVAGeneralPath.PathElement[] {
                new JAVAGeneralPath.MoveTo(0.0f, 2.0f),
                new JAVAGeneralPath.LineTo(2.0f, 2.0f),
                new JAVAGeneralPath.LineTo(3.0f, 1.0f),
                new JAVAGeneralPath.LineTo(4.0f, 1.0f),
                new JAVAGeneralPath.LineTo(5.0f, 0.0f),
                new JAVAGeneralPath.LineTo(6.0f, 2.0f),
                new JAVAGeneralPath.LineTo(8.0f, 2.0f),
                new JAVAGeneralPath.LineTo(8.0f, 0.0f),
                new JAVAGeneralPath.LineTo(0.0f, 0.0f),
                new JAVAGeneralPath.ClosePath()
            }));
            vg[17].translate(10.625, 0.0);
            vg[17].setColor(new Color(255, 0, 0, 255));
            vg[17].setLineWidth(0.125);
            vg[17].draw(new JAVAGeneralPath(1, new JAVAGeneralPath.PathElement[] {
                new JAVAGeneralPath.MoveTo(1.0f, 1.0f),
                new JAVAGeneralPath.LineTo(1.0f, 3.0f),
                new JAVAGeneralPath.LineTo(7.0f, 3.0f),
                new JAVAGeneralPath.LineTo(7.0f, 1.0f),
                new JAVAGeneralPath.LineTo(5.0f, 1.0f),
                new JAVAGeneralPath.LineTo(4.0f, 3.0f),
                new JAVAGeneralPath.LineTo(3.0f, 1.0f),
                new JAVAGeneralPath.ClosePath()
            }));
            Paint0s3.paint(vg);
        } // paint
    } // class Paint0s2

    private static class Paint0s3 {
        public static void paint(VectorGraphics[] vg) {
            vg[17].setColor(new Color(0, 0, 0, 255));
            vg[17].setLineWidth(0.375);
            vg[17].fill(new JAVAGeneralPath(1, new JAVAGeneralPath.PathElement[] {
                new JAVAGeneralPath.MoveTo(0.0f, 0.0f),
                new JAVAGeneralPath.LineTo(8.0f, 0.0f),
                new JAVAGeneralPath.LineTo(8.0f, 2.0f),
                new JAVAGeneralPath.LineTo(0.0f, 2.0f),
                new JAVAGeneralPath.LineTo(0.0f, 0.0f),
                new JAVAGeneralPath.ClosePath()
            }));
            vg[17].translate(10.625, 0.0);
            vg[17].setColor(new Color(255, 0, 0, 255));
            vg[17].setLineWidth(0.125);
            vg[17].draw(new JAVAGeneralPath(1, new JAVAGeneralPath.PathElement[] {
                new JAVAGeneralPath.MoveTo(1.0f, 1.0f),
                new JAVAGeneralPath.LineTo(7.0f, 1.0f),
                new JAVAGeneralPath.LineTo(7.0f, 3.0f),
                new JAVAGeneralPath.LineTo(1.0f, 3.0f),
                new JAVAGeneralPath.LineTo(1.0f, 1.0f),
                new JAVAGeneralPath.ClosePath()
            }));
            vg[17].setColor(new Color(0, 0, 0, 255));
            vg[17].setLineWidth(0.375);
            vg[17].fill(new JAVAGeneralPath(1, new JAVAGeneralPath.PathElement[] {
                new JAVAGeneralPath.MoveTo(0.0f, 2.0f),
                new JAVAGeneralPath.LineTo(2.0f, 2.0f),
                new JAVAGeneralPath.LineTo(3.0f, 1.0f),
                new JAVAGeneralPath.LineTo(5.0f, 1.0f),
                new JAVAGeneralPath.LineTo(6.0f, 2.0f),
                new JAVAGeneralPath.LineTo(8.0f, 2.0f),
                new JAVAGeneralPath.LineTo(8.0f, 0.0f),
                new JAVAGeneralPath.LineTo(0.0f, 0.0f),
                new JAVAGeneralPath.ClosePath()
            }));
            vg[17].translate(10.625, 0.0);
            vg[17].setColor(new Color(255, 0, 0, 255));
            vg[17].setLineWidth(0.125);
            vg[17].draw(new JAVAGeneralPath(1, new JAVAGeneralPath.PathElement[] {
                new JAVAGeneralPath.MoveTo(1.0f, 1.0f),
                new JAVAGeneralPath.LineTo(7.0f, 1.0f),
                new JAVAGeneralPath.LineTo(7.0f, 3.0f),
                new JAVAGeneralPath.LineTo(1.0f, 3.0f),
                new JAVAGeneralPath.LineTo(1.0f, 1.0f),
                new JAVAGeneralPath.ClosePath()
            }));
            vg[17].setColor(new Color(0, 0, 0, 255));
            vg[17].setLineWidth(0.375);
            vg[17].fill(new JAVAGeneralPath(1, new JAVAGeneralPath.PathElement[] {
                new JAVAGeneralPath.MoveTo(6.0f, 2.0f),
                new JAVAGeneralPath.CurveTo(6.0f, 3.1045694f, 5.1045694f, 4.0f, 4.0f, 4.0f),
                new JAVAGeneralPath.CurveTo(2.8954306f, 4.0f, 2.0f, 3.1045694f, 2.0f, 2.0f),
                new JAVAGeneralPath.CurveTo(2.0f, 0.8954305f, 2.8954306f, 0.0f, 4.0f, 0.0f),
                new JAVAGeneralPath.CurveTo(5.1045694f, 0.0f, 6.0f, 0.8954305f, 6.0f, 2.0f),
                new JAVAGeneralPath.ClosePath()
            }));
            vg[17].translate(10.625, 0.0);
            vg[17].setColor(new Color(255, 0, 0, 255));
            vg[17].setLineWidth(0.125);
            vg[17].draw(new JAVAGeneralPath(1, new JAVAGeneralPath.PathElement[] {
                new JAVAGeneralPath.MoveTo(1.0f, 1.0f),
                new JAVAGeneralPath.LineTo(7.0f, 1.0f),
                new JAVAGeneralPath.LineTo(7.0f, 3.0f),
                new JAVAGeneralPath.LineTo(1.0f, 3.0f),
                new JAVAGeneralPath.LineTo(1.0f, 1.0f),
                new JAVAGeneralPath.ClosePath()
            }));
            vg[17].setColor(new Color(0, 0, 0, 255));
            vg[17].setLineWidth(0.375);
            vg[17].fill(new JAVAGeneralPath(1, new JAVAGeneralPath.PathElement[] {
                new JAVAGeneralPath.MoveTo(0.0f, 2.0f),
                new JAVAGeneralPath.LineTo(3.0f, 2.0f),
                new JAVAGeneralPath.LineTo(4.0f, 1.0f),
                new JAVAGeneralPath.LineTo(5.0f, 2.0f),
                new JAVAGeneralPath.LineTo(8.0f, 2.0f),
                new JAVAGeneralPath.LineTo(8.0f, 0.0f),
                new JAVAGeneralPath.LineTo(0.0f, 0.0f),
                new JAVAGeneralPath.ClosePath()
            }));
            vg[17].translate(10.625, 0.0);
            vg[17].setColor(new Color(255, 0, 0, 255));
            vg[17].setLineWidth(0.125);
            vg[17].draw(new JAVAGeneralPath(1, new JAVAGeneralPath.PathElement[] {
                new JAVAGeneralPath.MoveTo(7.0f, 2.0f),
                new JAVAGeneralPath.CurveTo(7.0f, 2.5522847f, 5.656854f, 3.0f, 4.0f, 3.0f),
                new JAVAGeneralPath.CurveTo(2.3431458f, 3.0f, 1.0f, 2.5522847f, 1.0f, 2.0f),
                new JAVAGeneralPath.CurveTo(1.0f, 1.4477153f, 2.3431458f, 1.0f, 4.0f, 1.0f),
                new JAVAGeneralPath.CurveTo(5.656854f, 1.0f, 7.0f, 1.4477153f, 7.0f, 2.0f),
                new JAVAGeneralPath.ClosePath()
            }));
            vg[17].setColor(new Color(0, 0, 0, 255));
            vg[17].setLineWidth(0.375);
            vg[17].fill(new JAVAGeneralPath(1, new JAVAGeneralPath.PathElement[] {
                new JAVAGeneralPath.MoveTo(6.0f, 2.0f),
                new JAVAGeneralPath.CurveTo(6.0f, 3.1045694f, 5.1045694f, 4.0f, 4.0f, 4.0f),
                new JAVAGeneralPath.CurveTo(2.8954306f, 4.0f, 2.0f, 3.1045694f, 2.0f, 2.0f),
                new JAVAGeneralPath.CurveTo(2.0f, 0.8954305f, 2.8954306f, 0.0f, 4.0f, 0.0f),
                new JAVAGeneralPath.CurveTo(5.1045694f, 0.0f, 6.0f, 0.8954305f, 6.0f, 2.0f),
                new JAVAGeneralPath.ClosePath()
            }));
            vg[17].dispose();
            vg[18] = (VectorGraphics)vg[1].create();
            vg[18].drawString("JavaClip", 10, 420);
            vg[18].scale(8.0, 8.0);
            vg[18].translate(1.25, 51.25);
            vg[18].translate(10.625, 0.0);
            vg[19] = (VectorGraphics)vg[18].create();
            vg[19].setColor(new Color(255, 0, 0, 255));
            vg[19].setLineWidth(0.125);
            vg[19].draw(new JAVAGeneralPath(1, new JAVAGeneralPath.PathElement[] {
                new JAVAGeneralPath.MoveTo(1.0f, 1.0f),
                new JAVAGeneralPath.LineTo(7.0f, 1.0f),
                new JAVAGeneralPath.LineTo(7.0f, 3.0f),
                new JAVAGeneralPath.LineTo(1.0f, 3.0f),
                new JAVAGeneralPath.LineTo(1.0f, 1.0f),
                new JAVAGeneralPath.ClosePath()
            }));
            vg[19].clip(new JAVAGeneralPath(1, new JAVAGeneralPath.PathElement[] {
                new JAVAGeneralPath.MoveTo(1.0f, 1.0f),
                new JAVAGeneralPath.LineTo(7.0f, 1.0f),
                new JAVAGeneralPath.LineTo(7.0f, 3.0f),
                new JAVAGeneralPath.LineTo(1.0f, 3.0f),
                new JAVAGeneralPath.LineTo(1.0f, 1.0f),
                new JAVAGeneralPath.ClosePath()
            }));
            vg[19].setColor(new Color(0, 0, 0, 255));
            vg[19].setLineWidth(0.375);
            vg[19].fill(new JAVAGeneralPath(1, new JAVAGeneralPath.PathElement[] {
                new JAVAGeneralPath.MoveTo(0.0f, 2.0f),
                new JAVAGeneralPath.LineTo(2.0f, 2.0f),
                new JAVAGeneralPath.LineTo(3.0f, 1.0f),
                new JAVAGeneralPath.LineTo(4.0f, 1.0f),
                new JAVAGeneralPath.LineTo(5.0f, 0.0f),
                new JAVAGeneralPath.LineTo(6.0f, 2.0f),
                new JAVAGeneralPath.LineTo(8.0f, 2.0f),
                new JAVAGeneralPath.LineTo(8.0f, 0.0f),
                new JAVAGeneralPath.LineTo(0.0f, 0.0f),
                new JAVAGeneralPath.ClosePath()
            }));
            vg[19].dispose();
            vg[18].translate(10.625, 0.0);
            vg[20] = (VectorGraphics)vg[18].create();
            vg[20].setColor(new Color(255, 0, 0, 255));
            vg[20].setLineWidth(0.125);
            vg[20].draw(new JAVAGeneralPath(1, new JAVAGeneralPath.PathElement[] {
                new JAVAGeneralPath.MoveTo(1.0f, 1.0f),
                new JAVAGeneralPath.LineTo(1.0f, 3.0f),
                new JAVAGeneralPath.LineTo(7.0f, 3.0f),
                new JAVAGeneralPath.LineTo(7.0f, 1.0f),
                new JAVAGeneralPath.LineTo(5.0f, 1.0f),
                new JAVAGeneralPath.LineTo(4.0f, 3.0f),
                new JAVAGeneralPath.LineTo(3.0f, 1.0f),
                new JAVAGeneralPath.ClosePath()
            }));
            vg[20].clip(new JAVAGeneralPath(1, new JAVAGeneralPath.PathElement[] {
                new JAVAGeneralPath.MoveTo(1.0f, 1.0f),
                new JAVAGeneralPath.LineTo(1.0f, 3.0f),
                new JAVAGeneralPath.LineTo(7.0f, 3.0f),
                new JAVAGeneralPath.LineTo(7.0f, 1.0f),
                new JAVAGeneralPath.LineTo(5.0f, 1.0f),
                new JAVAGeneralPath.LineTo(4.0f, 3.0f),
                new JAVAGeneralPath.LineTo(3.0f, 1.0f),
                new JAVAGeneralPath.ClosePath()
            }));
            vg[20].setColor(new Color(0, 0, 0, 255));
            vg[20].setLineWidth(0.375);
            vg[20].fill(new JAVAGeneralPath(1, new JAVAGeneralPath.PathElement[] {
                new JAVAGeneralPath.MoveTo(0.0f, 0.0f),
                new JAVAGeneralPath.LineTo(8.0f, 0.0f),
                new JAVAGeneralPath.LineTo(8.0f, 2.0f),
                new JAVAGeneralPath.LineTo(0.0f, 2.0f),
                new JAVAGeneralPath.LineTo(0.0f, 0.0f),
                new JAVAGeneralPath.ClosePath()
            }));
            vg[20].dispose();
            vg[18].translate(10.625, 0.0);
            vg[21] = (VectorGraphics)vg[18].create();
            vg[21].setColor(new Color(255, 0, 0, 255));
            vg[21].setLineWidth(0.125);
            vg[21].draw(new JAVAGeneralPath(1, new JAVAGeneralPath.PathElement[] {
                new JAVAGeneralPath.MoveTo(1.0f, 1.0f),
                new JAVAGeneralPath.LineTo(7.0f, 1.0f),
                new JAVAGeneralPath.LineTo(7.0f, 3.0f),
                new JAVAGeneralPath.LineTo(1.0f, 3.0f),
                new JAVAGeneralPath.LineTo(1.0f, 1.0f),
                new JAVAGeneralPath.ClosePath()
            }));
            vg[21].clip(new JAVAGeneralPath(1, new JAVAGeneralPath.PathElement[] {
                new JAVAGeneralPath.MoveTo(1.0f, 1.0f),
                new JAVAGeneralPath.LineTo(7.0f, 1.0f),
                new JAVAGeneralPath.LineTo(7.0f, 3.0f),
                new JAVAGeneralPath.LineTo(1.0f, 3.0f),
                new JAVAGeneralPath.LineTo(1.0f, 1.0f),
                new JAVAGeneralPath.ClosePath()
            }));
            Paint0s4.paint(vg);
        } // paint
    } // class Paint0s3

    private static class Paint0s4 {
        public static void paint(VectorGraphics[] vg) {
            vg[21].setColor(new Color(0, 0, 0, 255));
            vg[21].setLineWidth(0.375);
            vg[21].fill(new JAVAGeneralPath(1, new JAVAGeneralPath.PathElement[] {
                new JAVAGeneralPath.MoveTo(0.0f, 2.0f),
                new JAVAGeneralPath.LineTo(2.0f, 2.0f),
                new JAVAGeneralPath.LineTo(3.0f, 1.0f),
                new JAVAGeneralPath.LineTo(5.0f, 1.0f),
                new JAVAGeneralPath.LineTo(6.0f, 2.0f),
                new JAVAGeneralPath.LineTo(8.0f, 2.0f),
                new JAVAGeneralPath.LineTo(8.0f, 0.0f),
                new JAVAGeneralPath.LineTo(0.0f, 0.0f),
                new JAVAGeneralPath.ClosePath()
            }));
            vg[21].dispose();
            vg[18].translate(10.625, 0.0);
            vg[22] = (VectorGraphics)vg[18].create();
            vg[22].setColor(new Color(255, 0, 0, 255));
            vg[22].setLineWidth(0.125);
            vg[22].draw(new JAVAGeneralPath(1, new JAVAGeneralPath.PathElement[] {
                new JAVAGeneralPath.MoveTo(1.0f, 1.0f),
                new JAVAGeneralPath.LineTo(7.0f, 1.0f),
                new JAVAGeneralPath.LineTo(7.0f, 3.0f),
                new JAVAGeneralPath.LineTo(1.0f, 3.0f),
                new JAVAGeneralPath.LineTo(1.0f, 1.0f),
                new JAVAGeneralPath.ClosePath()
            }));
            vg[22].clip(new JAVAGeneralPath(1, new JAVAGeneralPath.PathElement[] {
                new JAVAGeneralPath.MoveTo(1.0f, 1.0f),
                new JAVAGeneralPath.LineTo(7.0f, 1.0f),
                new JAVAGeneralPath.LineTo(7.0f, 3.0f),
                new JAVAGeneralPath.LineTo(1.0f, 3.0f),
                new JAVAGeneralPath.LineTo(1.0f, 1.0f),
                new JAVAGeneralPath.ClosePath()
            }));
            vg[22].setColor(new Color(0, 0, 0, 255));
            vg[22].setLineWidth(0.375);
            vg[22].fill(new JAVAGeneralPath(1, new JAVAGeneralPath.PathElement[] {
                new JAVAGeneralPath.MoveTo(6.0f, 2.0f),
                new JAVAGeneralPath.CurveTo(6.0f, 3.1045694f, 5.1045694f, 4.0f, 4.0f, 4.0f),
                new JAVAGeneralPath.CurveTo(2.8954306f, 4.0f, 2.0f, 3.1045694f, 2.0f, 2.0f),
                new JAVAGeneralPath.CurveTo(2.0f, 0.8954305f, 2.8954306f, 0.0f, 4.0f, 0.0f),
                new JAVAGeneralPath.CurveTo(5.1045694f, 0.0f, 6.0f, 0.8954305f, 6.0f, 2.0f),
                new JAVAGeneralPath.ClosePath()
            }));
            vg[22].dispose();
            vg[18].translate(10.625, 0.0);
            vg[23] = (VectorGraphics)vg[18].create();
            vg[23].setColor(new Color(255, 0, 0, 255));
            vg[23].setLineWidth(0.125);
            vg[23].draw(new JAVAGeneralPath(1, new JAVAGeneralPath.PathElement[] {
                new JAVAGeneralPath.MoveTo(1.0f, 1.0f),
                new JAVAGeneralPath.LineTo(7.0f, 1.0f),
                new JAVAGeneralPath.LineTo(7.0f, 3.0f),
                new JAVAGeneralPath.LineTo(1.0f, 3.0f),
                new JAVAGeneralPath.LineTo(1.0f, 1.0f),
                new JAVAGeneralPath.ClosePath()
            }));
            vg[23].clip(new JAVAGeneralPath(1, new JAVAGeneralPath.PathElement[] {
                new JAVAGeneralPath.MoveTo(1.0f, 1.0f),
                new JAVAGeneralPath.LineTo(7.0f, 1.0f),
                new JAVAGeneralPath.LineTo(7.0f, 3.0f),
                new JAVAGeneralPath.LineTo(1.0f, 3.0f),
                new JAVAGeneralPath.LineTo(1.0f, 1.0f),
                new JAVAGeneralPath.ClosePath()
            }));
            vg[23].setColor(new Color(0, 0, 0, 255));
            vg[23].setLineWidth(0.375);
            vg[23].fill(new JAVAGeneralPath(1, new JAVAGeneralPath.PathElement[] {
                new JAVAGeneralPath.MoveTo(0.0f, 2.0f),
                new JAVAGeneralPath.LineTo(3.0f, 2.0f),
                new JAVAGeneralPath.LineTo(4.0f, 1.0f),
                new JAVAGeneralPath.LineTo(5.0f, 2.0f),
                new JAVAGeneralPath.LineTo(8.0f, 2.0f),
                new JAVAGeneralPath.LineTo(8.0f, 0.0f),
                new JAVAGeneralPath.LineTo(0.0f, 0.0f),
                new JAVAGeneralPath.ClosePath()
            }));
            vg[23].dispose();
            vg[18].translate(10.625, 0.0);
            vg[24] = (VectorGraphics)vg[18].create();
            vg[24].setColor(new Color(255, 0, 0, 255));
            vg[24].setLineWidth(0.125);
            vg[24].draw(new JAVAGeneralPath(1, new JAVAGeneralPath.PathElement[] {
                new JAVAGeneralPath.MoveTo(7.0f, 2.0f),
                new JAVAGeneralPath.CurveTo(7.0f, 2.5522847f, 5.656854f, 3.0f, 4.0f, 3.0f),
                new JAVAGeneralPath.CurveTo(2.3431458f, 3.0f, 1.0f, 2.5522847f, 1.0f, 2.0f),
                new JAVAGeneralPath.CurveTo(1.0f, 1.4477153f, 2.3431458f, 1.0f, 4.0f, 1.0f),
                new JAVAGeneralPath.CurveTo(5.656854f, 1.0f, 7.0f, 1.4477153f, 7.0f, 2.0f),
                new JAVAGeneralPath.ClosePath()
            }));
            vg[24].clip(new JAVAGeneralPath(1, new JAVAGeneralPath.PathElement[] {
                new JAVAGeneralPath.MoveTo(7.0f, 2.0f),
                new JAVAGeneralPath.CurveTo(7.0f, 2.5522847f, 5.656854f, 3.0f, 4.0f, 3.0f),
                new JAVAGeneralPath.CurveTo(2.3431458f, 3.0f, 1.0f, 2.5522847f, 1.0f, 2.0f),
                new JAVAGeneralPath.CurveTo(1.0f, 1.4477153f, 2.3431458f, 1.0f, 4.0f, 1.0f),
                new JAVAGeneralPath.CurveTo(5.656854f, 1.0f, 7.0f, 1.4477153f, 7.0f, 2.0f),
                new JAVAGeneralPath.ClosePath()
            }));
            vg[24].setColor(new Color(0, 0, 0, 255));
            vg[24].setLineWidth(0.375);
            vg[24].fill(new JAVAGeneralPath(1, new JAVAGeneralPath.PathElement[] {
                new JAVAGeneralPath.MoveTo(6.0f, 2.0f),
                new JAVAGeneralPath.CurveTo(6.0f, 3.1045694f, 5.1045694f, 4.0f, 4.0f, 4.0f),
                new JAVAGeneralPath.CurveTo(2.8954306f, 4.0f, 2.0f, 3.1045694f, 2.0f, 2.0f),
                new JAVAGeneralPath.CurveTo(2.0f, 0.8954305f, 2.8954306f, 0.0f, 4.0f, 0.0f),
                new JAVAGeneralPath.CurveTo(5.1045694f, 0.0f, 6.0f, 0.8954305f, 6.0f, 2.0f),
                new JAVAGeneralPath.ClosePath()
            }));
            vg[24].dispose();
            vg[18].dispose();
            vg[25] = (VectorGraphics)vg[1].create();
            vg[25].drawString("AreaClip", 10, 520);
            vg[25].scale(8.0, 8.0);
            vg[25].translate(1.25, 63.75);
            vg[25].translate(10.625, 0.0);
            vg[26] = (VectorGraphics)vg[25].create();
            vg[26].setColor(new Color(255, 0, 0, 255));
            vg[26].setLineWidth(0.125);
            vg[26].draw(new JAVAGeneralPath(1, new JAVAGeneralPath.PathElement[] {
                new JAVAGeneralPath.MoveTo(1.0f, 1.0f),
                new JAVAGeneralPath.LineTo(7.0f, 1.0f),
                new JAVAGeneralPath.LineTo(7.0f, 3.0f),
                new JAVAGeneralPath.LineTo(1.0f, 3.0f),
                new JAVAGeneralPath.LineTo(1.0f, 1.0f),
                new JAVAGeneralPath.ClosePath()
            }));
            vg[26].setColor(new Color(0, 0, 0, 255));
            vg[26].setLineWidth(0.375);
            vg[26].fill(new JAVAGeneralPath(1, new JAVAGeneralPath.PathElement[] {
                new JAVAGeneralPath.MoveTo(1.0f, 1.0f),
                new JAVAGeneralPath.LineTo(1.0f, 2.0f),
                new JAVAGeneralPath.LineTo(2.0f, 2.0f),
                new JAVAGeneralPath.LineTo(3.0f, 1.0f),
                new JAVAGeneralPath.ClosePath(),
                new JAVAGeneralPath.MoveTo(5.5f, 1.0f),
                new JAVAGeneralPath.LineTo(6.0f, 2.0f),
                new JAVAGeneralPath.LineTo(7.0f, 2.0f),
                new JAVAGeneralPath.LineTo(7.0f, 1.0f),
                new JAVAGeneralPath.ClosePath()
            }));
            vg[26].dispose();
            vg[25].translate(10.625, 0.0);
            vg[27] = (VectorGraphics)vg[25].create();
            vg[27].setColor(new Color(255, 0, 0, 255));
            vg[27].setLineWidth(0.125);
            vg[27].draw(new JAVAGeneralPath(1, new JAVAGeneralPath.PathElement[] {
                new JAVAGeneralPath.MoveTo(1.0f, 1.0f),
                new JAVAGeneralPath.LineTo(1.0f, 3.0f),
                new JAVAGeneralPath.LineTo(7.0f, 3.0f),
                new JAVAGeneralPath.LineTo(7.0f, 1.0f),
                new JAVAGeneralPath.LineTo(5.0f, 1.0f),
                new JAVAGeneralPath.LineTo(4.0f, 3.0f),
                new JAVAGeneralPath.LineTo(3.0f, 1.0f),
                new JAVAGeneralPath.ClosePath()
            }));
            vg[27].setColor(new Color(0, 0, 0, 255));
            vg[27].setLineWidth(0.375);
            vg[27].fill(new JAVAGeneralPath(1, new JAVAGeneralPath.PathElement[] {
                new JAVAGeneralPath.MoveTo(1.0f, 1.0f),
                new JAVAGeneralPath.LineTo(1.0f, 2.0f),
                new JAVAGeneralPath.LineTo(3.5f, 2.0f),
                new JAVAGeneralPath.LineTo(3.0f, 1.0f),
                new JAVAGeneralPath.ClosePath(),
                new JAVAGeneralPath.MoveTo(5.0f, 1.0f),
                new JAVAGeneralPath.LineTo(4.5f, 2.0f),
                new JAVAGeneralPath.LineTo(7.0f, 2.0f),
                new JAVAGeneralPath.LineTo(7.0f, 1.0f),
                new JAVAGeneralPath.ClosePath()
            }));
            vg[27].dispose();
            vg[25].translate(10.625, 0.0);
            vg[28] = (VectorGraphics)vg[25].create();
            vg[28].setColor(new Color(255, 0, 0, 255));
            vg[28].setLineWidth(0.125);
            vg[28].draw(new JAVAGeneralPath(1, new JAVAGeneralPath.PathElement[] {
                new JAVAGeneralPath.MoveTo(1.0f, 1.0f),
                new JAVAGeneralPath.LineTo(7.0f, 1.0f),
                new JAVAGeneralPath.LineTo(7.0f, 3.0f),
                new JAVAGeneralPath.LineTo(1.0f, 3.0f),
                new JAVAGeneralPath.LineTo(1.0f, 1.0f),
                new JAVAGeneralPath.ClosePath()
            }));
            vg[28].setColor(new Color(0, 0, 0, 255));
            vg[28].setLineWidth(0.375);
            vg[28].fill(new JAVAGeneralPath(1, new JAVAGeneralPath.PathElement[] {
                new JAVAGeneralPath.MoveTo(1.0f, 1.0f),
                new JAVAGeneralPath.LineTo(1.0f, 2.0f),
                new JAVAGeneralPath.LineTo(2.0f, 2.0f),
                new JAVAGeneralPath.LineTo(3.0f, 1.0f),
                new JAVAGeneralPath.ClosePath(),
                new JAVAGeneralPath.MoveTo(5.0f, 1.0f),
                new JAVAGeneralPath.LineTo(6.0f, 2.0f),
                new JAVAGeneralPath.LineTo(7.0f, 2.0f),
                new JAVAGeneralPath.LineTo(7.0f, 1.0f),
                new JAVAGeneralPath.ClosePath()
            }));
            Paint0s5.paint(vg);
        } // paint
    } // class Paint0s4

    private static class Paint0s5 {
        public static void paint(VectorGraphics[] vg) {
            vg[28].dispose();
            vg[25].translate(10.625, 0.0);
            vg[29] = (VectorGraphics)vg[25].create();
            vg[29].setColor(new Color(255, 0, 0, 255));
            vg[29].setLineWidth(0.125);
            vg[29].draw(new JAVAGeneralPath(1, new JAVAGeneralPath.PathElement[] {
                new JAVAGeneralPath.MoveTo(1.0f, 1.0f),
                new JAVAGeneralPath.LineTo(7.0f, 1.0f),
                new JAVAGeneralPath.LineTo(7.0f, 3.0f),
                new JAVAGeneralPath.LineTo(1.0f, 3.0f),
                new JAVAGeneralPath.LineTo(1.0f, 1.0f),
                new JAVAGeneralPath.ClosePath()
            }));
            vg[29].setColor(new Color(0, 0, 0, 255));
            vg[29].setLineWidth(0.375);
            vg[29].fill(new JAVAGeneralPath(1, new JAVAGeneralPath.PathElement[] {
                new JAVAGeneralPath.MoveTo(2.2675643f, 1.0f),
                new JAVAGeneralPath.CurveTo(2.0973942f, 1.2941734f, 2.0f, 1.6357129f, 2.0f, 2.0f),
                new JAVAGeneralPath.CurveTo(2.0f, 2.3642871f, 2.0973942f, 2.7058265f, 2.2675643f, 3.0f),
                new JAVAGeneralPath.LineTo(5.7324357f, 3.0f),
                new JAVAGeneralPath.CurveTo(5.9026055f, 2.7058265f, 6.0f, 2.3642871f, 6.0f, 2.0f),
                new JAVAGeneralPath.CurveTo(6.0f, 1.6357129f, 5.9026055f, 1.2941734f, 5.7324357f, 1.0f),
                new JAVAGeneralPath.ClosePath()
            }));
            vg[29].dispose();
            vg[25].translate(10.625, 0.0);
            vg[30] = (VectorGraphics)vg[25].create();
            vg[30].setColor(new Color(255, 0, 0, 255));
            vg[30].setLineWidth(0.125);
            vg[30].draw(new JAVAGeneralPath(1, new JAVAGeneralPath.PathElement[] {
                new JAVAGeneralPath.MoveTo(1.0f, 1.0f),
                new JAVAGeneralPath.LineTo(7.0f, 1.0f),
                new JAVAGeneralPath.LineTo(7.0f, 3.0f),
                new JAVAGeneralPath.LineTo(1.0f, 3.0f),
                new JAVAGeneralPath.LineTo(1.0f, 1.0f),
                new JAVAGeneralPath.ClosePath()
            }));
            vg[30].setColor(new Color(0, 0, 0, 255));
            vg[30].setLineWidth(0.375);
            vg[30].fill(new JAVAGeneralPath(1, new JAVAGeneralPath.PathElement[] {
                new JAVAGeneralPath.MoveTo(1.0f, 1.0f),
                new JAVAGeneralPath.LineTo(1.0f, 2.0f),
                new JAVAGeneralPath.LineTo(3.0f, 2.0f),
                new JAVAGeneralPath.LineTo(4.0f, 1.0f),
                new JAVAGeneralPath.ClosePath(),
                new JAVAGeneralPath.MoveTo(4.0f, 1.0f),
                new JAVAGeneralPath.LineTo(5.0f, 2.0f),
                new JAVAGeneralPath.LineTo(7.0f, 2.0f),
                new JAVAGeneralPath.LineTo(7.0f, 1.0f),
                new JAVAGeneralPath.ClosePath()
            }));
            vg[30].dispose();
            vg[25].translate(10.625, 0.0);
            vg[31] = (VectorGraphics)vg[25].create();
            vg[31].setColor(new Color(255, 0, 0, 255));
            vg[31].setLineWidth(0.125);
            vg[31].draw(new JAVAGeneralPath(1, new JAVAGeneralPath.PathElement[] {
                new JAVAGeneralPath.MoveTo(7.0f, 2.0f),
                new JAVAGeneralPath.CurveTo(7.0f, 2.5522847f, 5.656854f, 3.0f, 4.0f, 3.0f),
                new JAVAGeneralPath.CurveTo(2.3431458f, 3.0f, 1.0f, 2.5522847f, 1.0f, 2.0f),
                new JAVAGeneralPath.CurveTo(1.0f, 1.4477153f, 2.3431458f, 1.0f, 4.0f, 1.0f),
                new JAVAGeneralPath.CurveTo(5.656854f, 1.0f, 7.0f, 1.4477153f, 7.0f, 2.0f),
                new JAVAGeneralPath.ClosePath()
            }));
            vg[31].setColor(new Color(0, 0, 0, 255));
            vg[31].setLineWidth(0.375);
            vg[31].fill(new JAVAGeneralPath(1, new JAVAGeneralPath.PathElement[] {
                new JAVAGeneralPath.MoveTo(4.0f, 1.0f),
                new JAVAGeneralPath.CurveTo(3.3075979f, 1.0f, 2.6699824f, 1.0781897f, 2.162285f, 1.2095255f),
                new JAVAGeneralPath.LineTo(2.162285f, 1.2095255f),
                new JAVAGeneralPath.CurveTo(2.0578518f, 1.4519914f, 2.0f, 1.7192397f, 2.0f, 2.0f),
                new JAVAGeneralPath.CurveTo(2.0f, 2.2807603f, 2.0578518f, 2.5480087f, 2.1622853f, 2.7904747f),
                new JAVAGeneralPath.LineTo(2.1622853f, 2.7904747f),
                new JAVAGeneralPath.CurveTo(2.6699827f, 2.9218102f, 3.307598f, 3.0f, 4.0f, 3.0f),
                new JAVAGeneralPath.CurveTo(4.692402f, 3.0f, 5.3300176f, 2.9218102f, 5.8377147f, 2.7904744f),
                new JAVAGeneralPath.LineTo(5.8377147f, 2.7904744f),
                new JAVAGeneralPath.CurveTo(5.942148f, 2.5480087f, 6.0f, 2.2807603f, 6.0f, 2.0f),
                new JAVAGeneralPath.CurveTo(6.0f, 1.7192397f, 5.942148f, 1.4519914f, 5.8377147f, 1.2095255f),
                new JAVAGeneralPath.LineTo(5.8377147f, 1.2095255f),
                new JAVAGeneralPath.CurveTo(5.3300176f, 1.0781897f, 4.692402f, 1.0f, 4.0f, 1.0f),
                new JAVAGeneralPath.ClosePath()
            }));
            vg[31].dispose();
            vg[25].dispose();
            vg[1].dispose();
        } // paint
    } // class Paint0s5

    private VectorGraphics vg[] = new VectorGraphics[32];

    public static void main(String[] args) throws Exception {
        new TestClip(args).runTest(600, 600);
    }
} // class
