// AUTOMATICALLY GENERATED by FreeHEP JAVAGraphics2D

package org.freehep.graphicsio.java.test;

import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import org.freehep.graphics2d.VectorGraphics;
import org.freehep.graphicsio.test.TestingPanel;

public class TestSymbols2D extends TestingPanel {

    public TestSymbols2D(String[] args) throws Exception {
        super(args);
        setName("TestSymbols2D");
    } // contructor

    public void paint(Graphics g) {
        vg[0] = VectorGraphics.create(g);
        vg[0].setCreator("FreeHEP JAVAGraphics2D");
        Paint0s0.paint(vg);
    } // paint

    private static class Paint0s0 {
        public static void paint(VectorGraphics[] vg) {
            vg[0].setColor(new Color(0, 0, 0, 255));
            vg[0].setFont(new Font("Dialog", 0, 12));
            vg[1] = (VectorGraphics)vg[0].create();
            vg[1].setClip(0, 0, 600, 600);
            vg[1].setColor(new Color(255, 0, 0, 255));
            vg[1].fillRect(0, 0, 600, 600);
            vg[1].setColor(new Color(0, 0, 0, 255));
            vg[1].setLineWidth(1);
            vg[1].drawSymbol(60, 37, 50, 0);
            vg[1].drawSymbol(180, 37, 50, 1);
            vg[1].drawSymbol(300, 37, 50, 2);
            vg[1].drawSymbol(420, 37, 50, 3);
            vg[1].drawSymbol(540, 37, 50, 4);
            vg[1].setLineWidth(5.0);
            vg[1].drawSymbol(60, 112, 50, 0);
            vg[1].drawSymbol(180, 112, 50, 1);
            vg[1].drawSymbol(300, 112, 50, 2);
            vg[1].drawSymbol(420, 112, 50, 3);
            vg[1].drawSymbol(540, 112, 50, 4);
            vg[1].setLineWidth(1);
            vg[1].drawSymbol(60, 187, 50, 5);
            vg[1].drawSymbol(180, 187, 50, 6);
            vg[1].drawSymbol(300, 187, 50, 7);
            vg[1].drawSymbol(420, 187, 50, 8);
            vg[1].drawSymbol(540, 187, 50, 9);
            vg[1].setLineWidth(5.0);
            vg[1].drawSymbol(60, 262, 50, 5);
            vg[1].drawSymbol(180, 262, 50, 6);
            vg[1].drawSymbol(300, 262, 50, 7);
            vg[1].drawSymbol(420, 262, 50, 8);
            vg[1].drawSymbol(540, 262, 50, 9);
            vg[1].setLineWidth(1);
            vg[1].fillSymbol(60, 337, 50, 5);
            vg[1].fillSymbol(180, 337, 50, 6);
            vg[1].fillSymbol(300, 337, 50, 7);
            vg[1].fillSymbol(420, 337, 50, 8);
            vg[1].fillSymbol(540, 337, 50, 9);
            vg[1].setLineWidth(5.0);
            vg[1].fillSymbol(60, 412, 50, 5);
            vg[1].fillSymbol(180, 412, 50, 6);
            vg[1].fillSymbol(300, 412, 50, 7);
            vg[1].fillSymbol(420, 412, 50, 8);
            vg[1].fillSymbol(540, 412, 50, 9);
            vg[1].setLineWidth(1);
            vg[1].setLineWidth(5.0);
            vg[1].dispose();
        } // paint
    } // class Paint0s0

    private VectorGraphics vg[] = new VectorGraphics[2];

    public static void main(String[] args) throws Exception {
        new TestSymbols2D(args).runTest(600, 600);
    }
} // class
