// AUTOMATICALLY GENERATED by FreeHEP JAVAGraphics2D

package org.freehep.graphicsio.java.test;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Font;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.TexturePaint;
import java.awt.geom.Point2D;
import java.awt.geom.Rectangle2D;
import java.awt.image.BufferedImage;
import org.freehep.graphics2d.TagString;
import org.freehep.graphics2d.VectorGraphics;
import org.freehep.graphicsio.java.JAVAGeneralPath;
import org.freehep.graphicsio.test.TestingPanel;

public class TestAll extends TestingPanel {

    public TestAll(String[] args) throws Exception {
        super(args);
        setName("TestAll");
    } // contructor

    public void paint(Graphics g) {
        vg[0] = VectorGraphics.create(g);
        vg[0].setCreator("FreeHEP JAVAGraphics2D");
        Paint0s0.paint(vg);
    } // paint

    private static class Paint0s0 {
        public static void paint(VectorGraphics[] vg) {
            vg[0].setColor(new Color(51, 51, 51, 255));
            vg[0].setFont(new Font("Dialog", 0, 12));
            vg[1] = (VectorGraphics)vg[0].create();
            vg[1].setClip(0, 0, 600, 600);
            vg[1].setColor(new Color(255, 255, 255, 255));
            vg[1].fillRect(0, 0, 600, 600);
            vg[1].setPaint(new GradientPaint(
                new Point2D.Double(0.0, 10.0), new Color(0, 0, 255, 255), 
                new Point2D.Double(600.0, 10.0), new Color(255, 255, 255, 255), false
            ));
            vg[1].fillRect(0.0, 10.0, 600.0, 30.0);
            vg[1].setFont(new Font("Helvetica", 1, 18));
            vg[1].setPaint(new GradientPaint(
                new Point2D.Double(0.0, 10.0), new Color(0, 0, 0, 255), 
                new Point2D.Double(600.0, 10.0), new Color(0, 0, 255, 255), false
            ));
            vg[1].drawString("Testing org.freehep.graphicsio.java.JAVAGraphics2D", 10, 30);
            vg[1].setColor(new Color(0, 0, 0, 255));
            vg[1].fillRect(37.5, 112.5, 150.0, 150.0);
            vg[1].setColor(new Color(255, 255, 255, 255));
            vg[1].fillOval(37.5, 112.5, 150.0, 150.0);
            vg[1].setColor(new Color(0, 0, 0, 255));
            vg[1].fillRect(59.46699141100894, 134.46699141100893, 106.06601717798212, 106.06601717798212);
            vg[1].setColor(new Color(255, 255, 255, 255));
            vg[1].fillOval(59.46699141100894, 134.46699141100893, 106.06601717798212, 106.06601717798212);
            vg[1].setColor(new Color(0, 0, 0, 255));
            vg[1].fillRect(75.0, 150.0, 74.99999999999999, 74.99999999999999);
            vg[1].setColor(new Color(255, 255, 255, 255));
            vg[1].fillOval(75.0, 150.0, 74.99999999999999, 74.99999999999999);
            vg[1].setColor(new Color(0, 0, 0, 255));
            vg[1].fillRect(85.98349570550448, 160.98349570550448, 53.03300858899105, 53.03300858899105);
            vg[1].setColor(new Color(255, 255, 255, 255));
            vg[1].fillOval(85.98349570550448, 160.98349570550448, 53.03300858899105, 53.03300858899105);
            vg[1].setColor(new Color(0, 0, 0, 255));
            vg[1].fillRect(93.75, 168.75, 37.499999999999986, 37.499999999999986);
            vg[1].setColor(new Color(255, 255, 255, 255));
            vg[1].fillOval(93.75, 168.75, 37.499999999999986, 37.499999999999986);
            vg[1].setColor(new Color(0, 0, 0, 255));
            vg[1].fillRect(99.24174785275224, 174.24174785275224, 26.51650429449552, 26.51650429449552);
            vg[1].setColor(new Color(255, 255, 255, 255));
            vg[1].fillOval(99.24174785275224, 174.24174785275224, 26.51650429449552, 26.51650429449552);
            vg[1].setColor(new Color(0, 0, 0, 255));
            vg[1].fillRect(103.125, 178.125, 18.74999999999999, 18.74999999999999);
            vg[1].setColor(new Color(255, 255, 255, 255));
            vg[1].fillOval(103.125, 178.125, 18.74999999999999, 18.74999999999999);
            vg[1].setColor(new Color(0, 0, 0, 255));
            vg[1].fillRect(105.87087392637612, 180.87087392637613, 13.258252147247758, 13.258252147247758);
            vg[1].setColor(new Color(255, 255, 255, 255));
            vg[1].fillOval(105.87087392637612, 180.87087392637613, 13.258252147247758, 13.258252147247758);
            vg[1].setColor(new Color(0, 0, 0, 255));
            vg[1].fillRect(107.8125, 182.8125, 9.374999999999993, 9.374999999999993);
            vg[1].setColor(new Color(255, 255, 255, 255));
            vg[1].fillOval(107.8125, 182.8125, 9.374999999999993, 9.374999999999993);
            vg[1].setColor(new Color(0, 0, 0, 255));
            vg[1].fillRect(109.18543696318807, 184.18543696318807, 6.629126073623878, 6.629126073623878);
            vg[1].setColor(new Color(255, 255, 255, 255));
            vg[1].fillOval(109.18543696318807, 184.18543696318807, 6.629126073623878, 6.629126073623878);
            vg[1].setColor(new Color(0, 0, 0, 255));
            vg[1].fillRect(110.15625, 185.15625, 4.6874999999999964, 4.6874999999999964);
            vg[1].setColor(new Color(255, 255, 255, 255));
            vg[1].fillOval(110.15625, 185.15625, 4.6874999999999964, 4.6874999999999964);
            vg[1].setColor(new Color(0, 0, 0, 255));
            vg[1].fillRect(110.84271848159403, 185.84271848159403, 3.314563036811939, 3.314563036811939);
            vg[1].setColor(new Color(255, 255, 255, 255));
            vg[1].fillOval(110.84271848159403, 185.84271848159403, 3.314563036811939, 3.314563036811939);
            vg[1].setColor(new Color(0, 0, 0, 255));
            vg[1].fillRect(111.328125, 186.328125, 2.3437499999999982, 2.3437499999999982);
            vg[1].setColor(new Color(255, 255, 255, 255));
            vg[1].fillOval(111.328125, 186.328125, 2.3437499999999982, 2.3437499999999982);
            vg[1].setColor(new Color(0, 0, 0, 255));
            vg[1].fillRect(111.67135924079702, 186.67135924079702, 1.6572815184059695, 1.6572815184059695);
            vg[1].setColor(new Color(255, 255, 255, 255));
            vg[1].fillOval(111.67135924079702, 186.67135924079702, 1.6572815184059695, 1.6572815184059695);
            vg[1].setColor(new Color(0, 0, 0, 255));
            vg[1].fillRect(111.9140625, 186.9140625, 1.1718749999999991, 1.1718749999999991);
            vg[1].setColor(new Color(255, 255, 255, 255));
            vg[1].fillOval(111.9140625, 186.9140625, 1.1718749999999991, 1.1718749999999991);
            vg[1].setColor(new Color(0, 0, 0, 255));
            vg[1].setFont(new Font("TimesRoman", 0, 11));
            vg[1].drawString(new TagString("The <i>drawString</i> methods in <i>VectorGraphics</i> support"), 225.0, 122.5);
            vg[1].drawString(new TagString("output of strings using a subset of the <b>HTML language</b>."), 225.0, 136.5);
            vg[1].setColor(new Color(255, 0, 0, 255));
            vg[1].drawSymbol(300.0, 187.5, 12.0, 0);
            vg[1].fillSymbol(300.0, 202.5, 10.0, 0);
            vg[1].drawSymbol(315.0, 187.5, 12.0, 1);
            vg[1].fillSymbol(315.0, 202.5, 10.0, 1);
            vg[1].drawSymbol(330.0, 187.5, 12.0, 2);
            vg[1].fillSymbol(330.0, 202.5, 10.0, 2);
            vg[1].drawSymbol(345.0, 187.5, 12.0, 3);
            vg[1].fillSymbol(345.0, 202.5, 10.0, 3);
            vg[1].drawSymbol(360.0, 187.5, 12.0, 4);
            vg[1].fillSymbol(360.0, 202.5, 10.0, 4);
            vg[1].drawSymbol(375.0, 187.5, 12.0, 5);
            vg[1].fillSymbol(375.0, 202.5, 10.0, 5);
            vg[1].drawSymbol(390.0, 187.5, 12.0, 6);
            vg[1].fillSymbol(390.0, 202.5, 10.0, 6);
            vg[1].drawSymbol(405.0, 187.5, 12.0, 7);
            vg[1].fillSymbol(405.0, 202.5, 10.0, 7);
            vg[1].drawSymbol(420.0, 187.5, 12.0, 8);
            vg[1].fillSymbol(420.0, 202.5, 10.0, 8);
            vg[1].drawSymbol(435.0, 187.5, 12.0, 9);
            vg[1].fillSymbol(435.0, 202.5, 10.0, 9);
            vg[1].setPaint(new TexturePaint(
                (BufferedImage)
                new BufferedImage(200, 200, BufferedImage.TYPE_INT_ARGB), new Rectangle2D.Double(0.0, 0.0, 200.0, 200.0)));
            vg[1].fillRect(0.0, 300.0, 300.0, 300.0);
            vg[1].setPaint(new Color(0, 0, 0, 255));
            vg[1].setFont(new Font("Impact", 1, 60));
            vg[1].drawString("\u2729Impact\u2729", 150.0, 450.0, 2, 0);
            vg[2] = (VectorGraphics)vg[1].create();
            vg[2].translate(300.0, 300.0);
            vg[2].setStroke(new BasicStroke(
                8.0f, 0, 
                2, 10.0f, 
                null, 0.0f
            ));
            vg[2].draw(new JAVAGeneralPath(1, new JAVAGeneralPath.PathElement[] {
                new JAVAGeneralPath.MoveTo(0.0f, 0.0f),
                new JAVAGeneralPath.LineTo(25.0f, 50.0f),
                new JAVAGeneralPath.LineTo(-25.0f, 50.0f),
                new JAVAGeneralPath.LineTo(25.0f, -50.0f),
                new JAVAGeneralPath.LineTo(-25.0f, -50.0f),
                new JAVAGeneralPath.ClosePath()
            }));
            vg[3] = (VectorGraphics)vg[2].create();
            vg[3].setColor(new Color(0, 0, 0, 255));
            vg[3].setStroke(new BasicStroke(
                3.0f, 1, 
                1, 10.0f, 
                new float[] {
                    10.0f, 5.0f, 2.0f, 5.0f
                }, 0.0f
            ));
            vg[3].rotate(0.6283185307179586);
            vg[3].draw(new JAVAGeneralPath(1, new JAVAGeneralPath.PathElement[] {
                new JAVAGeneralPath.MoveTo(0.0f, 0.0f),
                new JAVAGeneralPath.LineTo(25.0f, 50.0f),
                new JAVAGeneralPath.LineTo(-25.0f, 50.0f),
                new JAVAGeneralPath.LineTo(25.0f, -50.0f),
                new JAVAGeneralPath.LineTo(-25.0f, -50.0f),
                new JAVAGeneralPath.ClosePath()
            }));
            vg[3].dispose();
            vg[2].setLineWidth(1);
            vg[2].shear(0.5, 0.5);
            vg[2].draw(new JAVAGeneralPath(1, new JAVAGeneralPath.PathElement[] {
                new JAVAGeneralPath.MoveTo(0.0f, 0.0f),
                new JAVAGeneralPath.LineTo(25.0f, 50.0f),
                new JAVAGeneralPath.LineTo(-25.0f, 50.0f),
                new JAVAGeneralPath.LineTo(25.0f, -50.0f),
                new JAVAGeneralPath.LineTo(-25.0f, -50.0f),
                new JAVAGeneralPath.ClosePath()
            }));
            vg[2].dispose();
            vg[4] = (VectorGraphics)vg[1].create();
            vg[4].setColor(new Color(0, 0, 0, 255));
            vg[4].translate(450.0, 450.0);
            vg[4].fillOval(-60.0, -60.0, 120.0, 120.0);
            vg[4].setStroke(new BasicStroke(
                4.0f, 1, 
                1, 10.0f, 
                null, 0.0f
            ));
            vg[4].drawOval(-84.0, -84.0, 168.0, 168.0);
            vg[4].setFont(new Font("TimesRoman", 1, 16));
            vg[4].drawString("O", 0.0, -66.0);
            vg[4].rotate(0.7853981633974483);
            vg[4].drawString("R", 0.0, -66.0);
            vg[4].rotate(0.7853981633974483);
            vg[4].drawString("A", 0.0, -66.0);
            vg[4].rotate(0.7853981633974483);
            vg[4].drawString("E", 0.0, -66.0);
            vg[4].rotate(0.7853981633974483);
            vg[4].drawString("T", 0.0, -66.0);
            vg[4].rotate(0.7853981633974483);
            vg[4].drawString("L", 0.0, -66.0);
            vg[4].rotate(0.7853981633974483);
            vg[4].drawString("A", 0.0, -66.0);
            vg[4].rotate(0.7853981633974483);
            vg[4].drawString("B", 0.0, -66.0);
            vg[4].rotate(0.7853981633974483);
            vg[4].dispose();
            vg[1].dispose();
        } // paint
    } // class Paint0s0

    private VectorGraphics vg[] = new VectorGraphics[5];

    public static void main(String[] args) throws Exception {
        new TestAll(args).runTest(600, 600);
    }
} // class
