// AUTOMATICALLY GENERATED by FreeHEP JAVAGraphics2D

package org.freehep.graphicsio.java.test;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;

import org.freehep.graphics2d.VectorGraphics;
import org.freehep.graphicsio.java.JAVAGeneralPath;
import org.freehep.graphicsio.test.TestingPanel;

public class TestResolution extends TestingPanel {

    public TestResolution(String[] args) throws Exception {
        super(args);
        setName("TestResolution");
    } // contructor

    public void paint(Graphics g) {
        vg[0] = VectorGraphics.create(g);
        vg[0].setCreator("FreeHEP JAVAGraphics2D");
        Paint0s0.paint(vg);
    } // paint

    private static class Paint0s0 {
        public static void paint(VectorGraphics[] vg) {
            vg[0].setColor(new Color(51, 51, 51, 255));
            vg[0].setFont(new Font("Dialog", 0, 12));
            vg[1] = (VectorGraphics)vg[0].create();
            vg[1].setClip(0, 0, 600, 600);
            vg[1].setColor(new Color(255, 255, 255, 255));
            vg[1].fillRect(0, 0, 600, 600);
            vg[2] = (VectorGraphics)vg[1].create();
            vg[2].translate(0.0, 0.0);
            vg[2].translate(100.0, 60.0);
            vg[2].scale(30.0, 30.0);
            vg[2].scale(1.0E7, 1.0E7);
            vg[2].setStroke(new BasicStroke(
                5.0E-8f, 1, 
                1, 10.0f, 
                null, 0.0f
            ));
            vg[2].setColor(new Color(0, 0, 0, 255));
            vg[2].draw(new JAVAGeneralPath(1, new JAVAGeneralPath.PathElement[] {
                new JAVAGeneralPath.MoveTo(1.0E-7f, 0.0f),
                new JAVAGeneralPath.CurveTo(1.0E-7f, 5.5228476E-8f, 5.5228476E-8f, 1.0E-7f, 0.0f, 1.0E-7f),
                new JAVAGeneralPath.CurveTo(-5.5228476E-8f, 1.0E-7f, -1.0E-7f, 5.5228476E-8f, -1.0E-7f, 0.0f),
                new JAVAGeneralPath.CurveTo(-1.0E-7f, -5.5228476E-8f, -5.5228476E-8f, -1.0E-7f, 0.0f, -1.0E-7f),
                new JAVAGeneralPath.CurveTo(5.5228476E-8f, -1.0E-7f, 1.0E-7f, -5.5228476E-8f, 1.0E-7f, 0.0f),
                new JAVAGeneralPath.ClosePath()
            }));
            vg[2].dispose();
            vg[3] = (VectorGraphics)vg[1].create();
            vg[3].translate(0.0, 120.0);
            vg[3].translate(100.0, 60.0);
            vg[3].scale(30.0, 30.0);
            vg[3].scale(1000000.0, 1000000.0);
            vg[3].setStroke(new BasicStroke(
                5.0E-7f, 1, 
                1, 10.0f, 
                null, 0.0f
            ));
            vg[3].setColor(new Color(0, 0, 0, 255));
            vg[3].draw(new JAVAGeneralPath(1, new JAVAGeneralPath.PathElement[] {
                new JAVAGeneralPath.MoveTo(1.0E-6f, 0.0f),
                new JAVAGeneralPath.CurveTo(1.0E-6f, 5.5228475E-7f, 5.5228475E-7f, 1.0E-6f, 0.0f, 1.0E-6f),
                new JAVAGeneralPath.CurveTo(-5.5228475E-7f, 1.0E-6f, -1.0E-6f, 5.5228475E-7f, -1.0E-6f, 0.0f),
                new JAVAGeneralPath.CurveTo(-1.0E-6f, -5.5228475E-7f, -5.5228475E-7f, -1.0E-6f, 0.0f, -1.0E-6f),
                new JAVAGeneralPath.CurveTo(5.5228475E-7f, -1.0E-6f, 1.0E-6f, -5.5228475E-7f, 1.0E-6f, 0.0f),
                new JAVAGeneralPath.ClosePath()
            }));
            vg[3].dispose();
            vg[4] = (VectorGraphics)vg[1].create();
            vg[4].translate(0.0, 240.0);
            vg[4].translate(100.0, 60.0);
            vg[4].scale(30.0, 30.0);
            vg[4].scale(100000.00000000001, 100000.00000000001);
            vg[4].setStroke(new BasicStroke(
                5.0E-6f, 1, 
                1, 10.0f, 
                null, 0.0f
            ));
            vg[4].setColor(new Color(0, 0, 0, 255));
            vg[4].draw(new JAVAGeneralPath(1, new JAVAGeneralPath.PathElement[] {
                new JAVAGeneralPath.MoveTo(1.0E-5f, 0.0f),
                new JAVAGeneralPath.CurveTo(1.0E-5f, 5.5228475E-6f, 5.5228475E-6f, 1.0E-5f, 0.0f, 1.0E-5f),
                new JAVAGeneralPath.CurveTo(-5.5228475E-6f, 1.0E-5f, -1.0E-5f, 5.5228475E-6f, -1.0E-5f, 0.0f),
                new JAVAGeneralPath.CurveTo(-1.0E-5f, -5.5228475E-6f, -5.5228475E-6f, -1.0E-5f, 0.0f, -1.0E-5f),
                new JAVAGeneralPath.CurveTo(5.5228475E-6f, -1.0E-5f, 1.0E-5f, -5.5228475E-6f, 1.0E-5f, 0.0f),
                new JAVAGeneralPath.ClosePath()
            }));
            vg[4].dispose();
            vg[5] = (VectorGraphics)vg[1].create();
            vg[5].translate(0.0, 360.0);
            vg[5].translate(100.0, 60.0);
            vg[5].scale(30.0, 30.0);
            vg[5].scale(10000.0, 10000.0);
            vg[5].setStroke(new BasicStroke(
                5.0E-5f, 1, 
                1, 10.0f, 
                null, 0.0f
            ));
            vg[5].setColor(new Color(0, 0, 0, 255));
            vg[5].draw(new JAVAGeneralPath(1, new JAVAGeneralPath.PathElement[] {
                new JAVAGeneralPath.MoveTo(1.0E-4f, 0.0f),
                new JAVAGeneralPath.CurveTo(1.0E-4f, 5.5228476E-5f, 5.5228476E-5f, 1.0E-4f, 0.0f, 1.0E-4f),
                new JAVAGeneralPath.CurveTo(-5.5228476E-5f, 1.0E-4f, -1.0E-4f, 5.5228476E-5f, -1.0E-4f, 0.0f),
                new JAVAGeneralPath.CurveTo(-1.0E-4f, -5.5228476E-5f, -5.5228476E-5f, -1.0E-4f, 0.0f, -1.0E-4f),
                new JAVAGeneralPath.CurveTo(5.5228476E-5f, -1.0E-4f, 1.0E-4f, -5.5228476E-5f, 1.0E-4f, 0.0f),
                new JAVAGeneralPath.ClosePath()
            }));
            vg[5].dispose();
            vg[6] = (VectorGraphics)vg[1].create();
            vg[6].translate(0.0, 480.0);
            vg[6].translate(100.0, 60.0);
            vg[6].scale(30.0, 30.0);
            vg[6].scale(1000.0, 1000.0);
            vg[6].setStroke(new BasicStroke(
                5.0E-4f, 1, 
                1, 10.0f, 
                null, 0.0f
            ));
            vg[6].setColor(new Color(0, 0, 0, 255));
            vg[6].draw(new JAVAGeneralPath(1, new JAVAGeneralPath.PathElement[] {
                new JAVAGeneralPath.MoveTo(0.0010f, 0.0f),
                new JAVAGeneralPath.CurveTo(0.0010f, 5.5228476E-4f, 5.5228476E-4f, 0.0010f, 0.0f, 0.0010f),
                new JAVAGeneralPath.CurveTo(-5.5228476E-4f, 0.0010f, -0.0010f, 5.5228476E-4f, -0.0010f, 0.0f),
                new JAVAGeneralPath.CurveTo(-0.0010f, -5.5228476E-4f, -5.5228476E-4f, -0.0010f, 0.0f, -0.0010f),
                new JAVAGeneralPath.CurveTo(5.5228476E-4f, -0.0010f, 0.0010f, -5.5228476E-4f, 0.0010f, 0.0f),
                new JAVAGeneralPath.ClosePath()
            }));
            vg[6].dispose();
            vg[7] = (VectorGraphics)vg[1].create();
            vg[7].translate(200.0, 0.0);
            vg[7].translate(100.0, 60.0);
            vg[7].scale(30.0, 30.0);
            vg[7].scale(100.0, 100.0);
            vg[7].setStroke(new BasicStroke(
                0.0050f, 1, 
                1, 10.0f, 
                null, 0.0f
            ));
            vg[7].setColor(new Color(0, 0, 0, 255));
            vg[7].draw(new JAVAGeneralPath(1, new JAVAGeneralPath.PathElement[] {
                new JAVAGeneralPath.MoveTo(0.01f, 0.0f),
                new JAVAGeneralPath.CurveTo(0.01f, 0.0055228476f, 0.0055228476f, 0.01f, 0.0f, 0.01f),
                new JAVAGeneralPath.CurveTo(-0.0055228476f, 0.01f, -0.01f, 0.0055228476f, -0.01f, 0.0f),
                new JAVAGeneralPath.CurveTo(-0.01f, -0.0055228476f, -0.0055228476f, -0.01f, 0.0f, -0.01f),
                new JAVAGeneralPath.CurveTo(0.0055228476f, -0.01f, 0.01f, -0.0055228476f, 0.01f, 0.0f),
                new JAVAGeneralPath.ClosePath()
            }));
            vg[7].dispose();
            vg[8] = (VectorGraphics)vg[1].create();
            vg[8].translate(200.0, 120.0);
            vg[8].translate(100.0, 60.0);
            vg[8].scale(30.0, 30.0);
            vg[8].scale(10.0, 10.0);
            vg[8].setStroke(new BasicStroke(
                0.05f, 1, 
                1, 10.0f, 
                null, 0.0f
            ));
            vg[8].setColor(new Color(0, 0, 0, 255));
            vg[8].draw(new JAVAGeneralPath(1, new JAVAGeneralPath.PathElement[] {
                new JAVAGeneralPath.MoveTo(0.1f, 0.0f),
                new JAVAGeneralPath.CurveTo(0.1f, 0.055228475f, 0.055228475f, 0.1f, 0.0f, 0.1f),
                new JAVAGeneralPath.CurveTo(-0.055228475f, 0.1f, -0.1f, 0.055228475f, -0.1f, 0.0f),
                new JAVAGeneralPath.CurveTo(-0.1f, -0.055228475f, -0.055228475f, -0.1f, 0.0f, -0.1f),
                new JAVAGeneralPath.CurveTo(0.055228475f, -0.1f, 0.1f, -0.055228475f, 0.1f, 0.0f),
                new JAVAGeneralPath.ClosePath()
            }));
            vg[8].dispose();
            vg[9] = (VectorGraphics)vg[1].create();
            vg[9].translate(200.0, 240.0);
            vg[9].translate(100.0, 60.0);
            vg[9].scale(30.0, 30.0);
            vg[9].scale(1.0, 1.0);
            vg[9].setStroke(new BasicStroke(
                0.5f, 1, 
                1, 10.0f, 
                null, 0.0f
            ));
            vg[9].setColor(new Color(0, 0, 0, 255));
            vg[9].draw(new JAVAGeneralPath(1, new JAVAGeneralPath.PathElement[] {
                new JAVAGeneralPath.MoveTo(1.0f, 0.0f),
                new JAVAGeneralPath.CurveTo(1.0f, 0.5522848f, 0.5522848f, 1.0f, 0.0f, 1.0f),
                new JAVAGeneralPath.CurveTo(-0.5522848f, 1.0f, -1.0f, 0.5522848f, -1.0f, 0.0f),
                new JAVAGeneralPath.CurveTo(-1.0f, -0.5522848f, -0.5522848f, -1.0f, 0.0f, -1.0f),
                new JAVAGeneralPath.CurveTo(0.5522848f, -1.0f, 1.0f, -0.5522848f, 1.0f, 0.0f),
                new JAVAGeneralPath.ClosePath()
            }));
            vg[9].dispose();
            vg[10] = (VectorGraphics)vg[1].create();
            vg[10].translate(200.0, 360.0);
            vg[10].translate(100.0, 60.0);
            vg[10].scale(30.0, 30.0);
            vg[10].scale(0.1, 0.1);
            vg[10].setStroke(new BasicStroke(
                5.0f, 1, 
                1, 10.0f, 
                null, 0.0f
            ));
            vg[10].setColor(new Color(0, 0, 0, 255));
            vg[10].draw(new JAVAGeneralPath(1, new JAVAGeneralPath.PathElement[] {
                new JAVAGeneralPath.MoveTo(10.0f, 0.0f),
                new JAVAGeneralPath.CurveTo(10.0f, 5.5228477f, 5.5228477f, 10.0f, 0.0f, 10.0f),
                new JAVAGeneralPath.CurveTo(-5.5228477f, 10.0f, -10.0f, 5.5228477f, -10.0f, 0.0f),
                new JAVAGeneralPath.CurveTo(-10.0f, -5.5228477f, -5.5228477f, -10.0f, 0.0f, -10.0f),
                new JAVAGeneralPath.CurveTo(5.5228477f, -10.0f, 10.0f, -5.5228477f, 10.0f, 0.0f),
                new JAVAGeneralPath.ClosePath()
            }));
            Paint0s1.paint(vg);
        } // paint
    } // class Paint0s0

    private static class Paint0s1 {
        public static void paint(VectorGraphics[] vg) {
            vg[10].dispose();
            vg[11] = (VectorGraphics)vg[1].create();
            vg[11].translate(200.0, 480.0);
            vg[11].translate(100.0, 60.0);
            vg[11].scale(30.0, 30.0);
            vg[11].scale(0.01, 0.01);
            vg[11].setStroke(new BasicStroke(
                50.0f, 1, 
                1, 10.0f, 
                null, 0.0f
            ));
            vg[11].setColor(new Color(0, 0, 0, 255));
            vg[11].draw(new JAVAGeneralPath(1, new JAVAGeneralPath.PathElement[] {
                new JAVAGeneralPath.MoveTo(100.0f, 0.0f),
                new JAVAGeneralPath.CurveTo(100.0f, 55.228474f, 55.228474f, 100.0f, 0.0f, 100.0f),
                new JAVAGeneralPath.CurveTo(-55.228474f, 100.0f, -100.0f, 55.228474f, -100.0f, 0.0f),
                new JAVAGeneralPath.CurveTo(-100.0f, -55.228474f, -55.228474f, -100.0f, 0.0f, -100.0f),
                new JAVAGeneralPath.CurveTo(55.228474f, -100.0f, 100.0f, -55.228474f, 100.0f, 0.0f),
                new JAVAGeneralPath.ClosePath()
            }));
            vg[11].dispose();
            vg[12] = (VectorGraphics)vg[1].create();
            vg[12].translate(400.0, 0.0);
            vg[12].translate(100.0, 60.0);
            vg[12].scale(30.0, 30.0);
            vg[12].scale(0.0010, 0.0010);
            vg[12].setStroke(new BasicStroke(
                500.0f, 1, 
                1, 10.0f, 
                null, 0.0f
            ));
            vg[12].setColor(new Color(0, 0, 0, 255));
            vg[12].draw(new JAVAGeneralPath(1, new JAVAGeneralPath.PathElement[] {
                new JAVAGeneralPath.MoveTo(1000.0f, 0.0f),
                new JAVAGeneralPath.CurveTo(1000.0f, 552.2847f, 552.2847f, 1000.0f, 0.0f, 1000.0f),
                new JAVAGeneralPath.CurveTo(-552.2847f, 1000.0f, -1000.0f, 552.2847f, -1000.0f, 0.0f),
                new JAVAGeneralPath.CurveTo(-1000.0f, -552.2847f, -552.2847f, -1000.0f, 0.0f, -1000.0f),
                new JAVAGeneralPath.CurveTo(552.2847f, -1000.0f, 1000.0f, -552.2847f, 1000.0f, 0.0f),
                new JAVAGeneralPath.ClosePath()
            }));
            vg[12].dispose();
            vg[13] = (VectorGraphics)vg[1].create();
            vg[13].translate(400.0, 120.0);
            vg[13].translate(100.0, 60.0);
            vg[13].scale(30.0, 30.0);
            vg[13].scale(1.0E-4, 1.0E-4);
            vg[13].setStroke(new BasicStroke(
                5000.0f, 1, 
                1, 10.0f, 
                null, 0.0f
            ));
            vg[13].setColor(new Color(0, 0, 0, 255));
            vg[13].draw(new JAVAGeneralPath(1, new JAVAGeneralPath.PathElement[] {
                new JAVAGeneralPath.MoveTo(10000.0f, 0.0f),
                new JAVAGeneralPath.CurveTo(10000.0f, 5522.8477f, 5522.8477f, 10000.0f, 0.0f, 10000.0f),
                new JAVAGeneralPath.CurveTo(-5522.8477f, 10000.0f, -10000.0f, 5522.8477f, -10000.0f, 0.0f),
                new JAVAGeneralPath.CurveTo(-10000.0f, -5522.8477f, -5522.8477f, -10000.0f, 0.0f, -10000.0f),
                new JAVAGeneralPath.CurveTo(5522.8477f, -10000.0f, 10000.0f, -5522.8477f, 10000.0f, 0.0f),
                new JAVAGeneralPath.ClosePath()
            }));
            vg[13].dispose();
            vg[14] = (VectorGraphics)vg[1].create();
            vg[14].translate(400.0, 240.0);
            vg[14].translate(100.0, 60.0);
            vg[14].scale(30.0, 30.0);
            vg[14].scale(1.0E-5, 1.0E-5);
            vg[14].setStroke(new BasicStroke(
                50000.0f, 1, 
                1, 10.0f, 
                null, 0.0f
            ));
            vg[14].setColor(new Color(0, 0, 0, 255));
            vg[14].draw(new JAVAGeneralPath(1, new JAVAGeneralPath.PathElement[] {
                new JAVAGeneralPath.MoveTo(100000.0f, 0.0f),
                new JAVAGeneralPath.CurveTo(100000.0f, 55228.477f, 55228.477f, 100000.0f, 0.0f, 100000.0f),
                new JAVAGeneralPath.CurveTo(-55228.477f, 100000.0f, -100000.0f, 55228.477f, -100000.0f, 0.0f),
                new JAVAGeneralPath.CurveTo(-100000.0f, -55228.477f, -55228.477f, -100000.0f, 0.0f, -100000.0f),
                new JAVAGeneralPath.CurveTo(55228.477f, -100000.0f, 100000.0f, -55228.477f, 100000.0f, 0.0f),
                new JAVAGeneralPath.ClosePath()
            }));
            vg[14].dispose();
            vg[15] = (VectorGraphics)vg[1].create();
            vg[15].translate(400.0, 360.0);
            vg[15].translate(100.0, 60.0);
            vg[15].scale(30.0, 30.0);
            vg[15].scale(1.0E-6, 1.0E-6);
            vg[15].setStroke(new BasicStroke(
                500000.0f, 1, 
                1, 10.0f, 
                null, 0.0f
            ));
            vg[15].setColor(new Color(0, 0, 0, 255));
            vg[15].draw(new JAVAGeneralPath(1, new JAVAGeneralPath.PathElement[] {
                new JAVAGeneralPath.MoveTo(1000000.0f, 0.0f),
                new JAVAGeneralPath.CurveTo(1000000.0f, 552284.75f, 552284.75f, 1000000.0f, 0.0f, 1000000.0f),
                new JAVAGeneralPath.CurveTo(-552284.75f, 1000000.0f, -1000000.0f, 552284.75f, -1000000.0f, 0.0f),
                new JAVAGeneralPath.CurveTo(-1000000.0f, -552284.75f, -552284.75f, -1000000.0f, 0.0f, -1000000.0f),
                new JAVAGeneralPath.CurveTo(552284.75f, -1000000.0f, 1000000.0f, -552284.75f, 1000000.0f, 0.0f),
                new JAVAGeneralPath.ClosePath()
            }));
            vg[15].dispose();
            vg[16] = (VectorGraphics)vg[1].create();
            vg[16].translate(400.0, 480.0);
            vg[16].translate(100.0, 60.0);
            vg[16].scale(30.0, 30.0);
            vg[16].scale(1.0E-7, 1.0E-7);
            vg[16].setStroke(new BasicStroke(
                5000000.0f, 1, 
                1, 10.0f, 
                null, 0.0f
            ));
            vg[16].setColor(new Color(0, 0, 0, 255));
            vg[16].draw(new JAVAGeneralPath(1, new JAVAGeneralPath.PathElement[] {
                new JAVAGeneralPath.MoveTo(1.0E7f, 0.0f),
                new JAVAGeneralPath.CurveTo(1.0E7f, 5522847.5f, 5522847.5f, 1.0E7f, 0.0f, 1.0E7f),
                new JAVAGeneralPath.CurveTo(-5522847.5f, 1.0E7f, -1.0E7f, 5522847.5f, -1.0E7f, 0.0f),
                new JAVAGeneralPath.CurveTo(-1.0E7f, -5522847.5f, -5522847.5f, -1.0E7f, 0.0f, -1.0E7f),
                new JAVAGeneralPath.CurveTo(5522847.5f, -1.0E7f, 1.0E7f, -5522847.5f, 1.0E7f, 0.0f),
                new JAVAGeneralPath.ClosePath()
            }));
            vg[16].dispose();
            vg[1].dispose();
        } // paint
    } // class Paint0s1

    private VectorGraphics vg[] = new VectorGraphics[17];

    public static void main(String[] args) throws Exception {
        new TestResolution(args).runTest(600, 600);
    }
} // class
