// AUTOMATICALLY GENERATED by FreeHEP JAVAGraphics2D

package org.freehep.graphicsio.java.test;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import org.freehep.graphics2d.VectorGraphics;
import org.freehep.graphicsio.java.JAVAGeneralPath;
import org.freehep.graphicsio.test.TestingPanel;

public class TestCustomStrokes extends TestingPanel {

    public TestCustomStrokes(String[] args) throws Exception {
        super(args);
        setName("TestCustomStrokes");
    } // contructor

    public void paint(Graphics g) {
        vg[0] = VectorGraphics.create(g);
        vg[0].setCreator("FreeHEP JAVAGraphics2D");
        Paint0s0.paint(vg);
    } // paint

    private static class Paint0s0 {
        public static void paint(VectorGraphics[] vg) {
            vg[0].setColor(new Color(0, 0, 0, 255));
            vg[0].setFont(new Font("Lucida Grande", 0, 13));
            vg[1] = (VectorGraphics)vg[0].create();
            vg[1].setClip(0, 0, 600, 600);
            vg[2] = (VectorGraphics)vg[1].create();
            vg[2].setColor(new Color(0, 0, 0, 255));
            vg[2].translate(10, 175);
            vg[2].setStroke(new BasicStroke(
                4.0f, 2, 
                0, 10.0f, 
                null, 0.0f
            ));
            vg[2].draw(new JAVAGeneralPath(1, new JAVAGeneralPath.PathElement[] {
                new JAVAGeneralPath.MoveTo(2.4169922f, -3.8085938f),
                new JAVAGeneralPath.QuadTo(8.496094f, -4.0283203f, 11.1328125f, -5.419922f),
                new JAVAGeneralPath.QuadTo(15.600586f, -7.763672f, 15.600586f, -14.355469f),
                new JAVAGeneralPath.LineTo(15.600586f, -86.93848f),
                new JAVAGeneralPath.QuadTo(15.600586f, -93.53027f, 11.425781f, -95.80078f),
                new JAVAGeneralPath.QuadTo(8.935547f, -97.19238f, 2.4169922f, -97.55859f),
                new JAVAGeneralPath.LineTo(2.4169922f, -101.36719f),
                new JAVAGeneralPath.LineTo(48.779297f, -101.36719f),
                new JAVAGeneralPath.QuadTo(62.182617f, -101.36719f, 71.04492f, -98.291016f),
                new JAVAGeneralPath.QuadTo(87.74414f, -92.50488f, 87.74414f, -77.197266f),
                new JAVAGeneralPath.QuadTo(87.74414f, -67.89551f, 80.96924f, -62.438965f),
                new JAVAGeneralPath.QuadTo(74.194336f, -56.98242f, 66.28418f, -55.51758f),
                new JAVAGeneralPath.LineTo(66.28418f, -54.125977f),
                new JAVAGeneralPath.QuadTo(74.63379f, -52.51465f, 80.78613f, -48.706055f),
                new JAVAGeneralPath.QuadTo(92.79785f, -41.23535f, 92.79785f, -27.905273f),
                new JAVAGeneralPath.QuadTo(92.79785f, -15.454102f, 81.29883f, -7.727051f),
                new JAVAGeneralPath.QuadTo(69.799805f, 0.0f, 50.683594f, 0.0f),
                new JAVAGeneralPath.LineTo(2.4169922f, 0.0f),
                new JAVAGeneralPath.ClosePath(),
                new JAVAGeneralPath.MoveTo(39.55078f, -55.88379f),
                new JAVAGeneralPath.QuadTo(53.466797f, -55.88379f, 58.22754f, -60.424805f),
                new JAVAGeneralPath.QuadTo(62.98828f, -64.96582f, 62.98828f, -76.538086f),
                new JAVAGeneralPath.QuadTo(62.98828f, -85.10742f, 59.87549f, -90.9668f),
                new JAVAGeneralPath.QuadTo(56.762695f, -96.82617f, 47.90039f, -96.82617f),
                new JAVAGeneralPath.QuadTo(43.21289f, -96.82617f, 41.381836f, -95.251465f),
                new JAVAGeneralPath.QuadTo(39.55078f, -93.67676f, 39.55078f, -89.575195f),
                new JAVAGeneralPath.LineTo(39.55078f, -55.88379f),
                new JAVAGeneralPath.ClosePath(),
                new JAVAGeneralPath.MoveTo(39.55078f, -13.842773f),
                new JAVAGeneralPath.QuadTo(39.624023f, -9.887695f, 40.722656f, -8.056641f),
                new JAVAGeneralPath.QuadTo(42.55371f, -4.8339844f, 47.753906f, -4.8339844f),
                new JAVAGeneralPath.QuadTo(58.374023f, -4.8339844f, 62.65869f, -10.620117f),
                new JAVAGeneralPath.QuadTo(66.94336f, -16.40625f, 66.94336f, -27.09961f),
                new JAVAGeneralPath.QuadTo(66.94336f, -43.066406f, 57.495117f, -48.339844f),
                new JAVAGeneralPath.QuadTo(51.782227f, -51.5625f, 39.55078f, -51.342773f),
                new JAVAGeneralPath.LineTo(39.55078f, -13.842773f),
                new JAVAGeneralPath.ClosePath()
            }));
            vg[2].translate(100, 0);
            System.err.println("class org.freehep.graphicsio.java.JAVAGraphics2D: setStroke(Stroke) not implemented.");
            vg[2].draw(new JAVAGeneralPath(1, new JAVAGeneralPath.PathElement[] {
                new JAVAGeneralPath.MoveTo(2.4169922f, -3.8085938f),
                new JAVAGeneralPath.QuadTo(8.496094f, -4.0283203f, 11.1328125f, -5.419922f),
                new JAVAGeneralPath.QuadTo(15.600586f, -7.763672f, 15.600586f, -14.355469f),
                new JAVAGeneralPath.LineTo(15.600586f, -86.93848f),
                new JAVAGeneralPath.QuadTo(15.600586f, -93.53027f, 11.425781f, -95.80078f),
                new JAVAGeneralPath.QuadTo(8.935547f, -97.19238f, 2.4169922f, -97.55859f),
                new JAVAGeneralPath.LineTo(2.4169922f, -101.36719f),
                new JAVAGeneralPath.LineTo(48.779297f, -101.36719f),
                new JAVAGeneralPath.QuadTo(62.182617f, -101.36719f, 71.04492f, -98.291016f),
                new JAVAGeneralPath.QuadTo(87.74414f, -92.50488f, 87.74414f, -77.197266f),
                new JAVAGeneralPath.QuadTo(87.74414f, -67.89551f, 80.96924f, -62.438965f),
                new JAVAGeneralPath.QuadTo(74.194336f, -56.98242f, 66.28418f, -55.51758f),
                new JAVAGeneralPath.LineTo(66.28418f, -54.125977f),
                new JAVAGeneralPath.QuadTo(74.63379f, -52.51465f, 80.78613f, -48.706055f),
                new JAVAGeneralPath.QuadTo(92.79785f, -41.23535f, 92.79785f, -27.905273f),
                new JAVAGeneralPath.QuadTo(92.79785f, -15.454102f, 81.29883f, -7.727051f),
                new JAVAGeneralPath.QuadTo(69.799805f, 0.0f, 50.683594f, 0.0f),
                new JAVAGeneralPath.LineTo(2.4169922f, 0.0f),
                new JAVAGeneralPath.ClosePath(),
                new JAVAGeneralPath.MoveTo(39.55078f, -55.88379f),
                new JAVAGeneralPath.QuadTo(53.466797f, -55.88379f, 58.22754f, -60.424805f),
                new JAVAGeneralPath.QuadTo(62.98828f, -64.96582f, 62.98828f, -76.538086f),
                new JAVAGeneralPath.QuadTo(62.98828f, -85.10742f, 59.87549f, -90.9668f),
                new JAVAGeneralPath.QuadTo(56.762695f, -96.82617f, 47.90039f, -96.82617f),
                new JAVAGeneralPath.QuadTo(43.21289f, -96.82617f, 41.381836f, -95.251465f),
                new JAVAGeneralPath.QuadTo(39.55078f, -93.67676f, 39.55078f, -89.575195f),
                new JAVAGeneralPath.LineTo(39.55078f, -55.88379f),
                new JAVAGeneralPath.ClosePath(),
                new JAVAGeneralPath.MoveTo(39.55078f, -13.842773f),
                new JAVAGeneralPath.QuadTo(39.624023f, -9.887695f, 40.722656f, -8.056641f),
                new JAVAGeneralPath.QuadTo(42.55371f, -4.8339844f, 47.753906f, -4.8339844f),
                new JAVAGeneralPath.QuadTo(58.374023f, -4.8339844f, 62.65869f, -10.620117f),
                new JAVAGeneralPath.QuadTo(66.94336f, -16.40625f, 66.94336f, -27.09961f),
                new JAVAGeneralPath.QuadTo(66.94336f, -43.066406f, 57.495117f, -48.339844f),
                new JAVAGeneralPath.QuadTo(51.782227f, -51.5625f, 39.55078f, -51.342773f),
                new JAVAGeneralPath.LineTo(39.55078f, -13.842773f),
                new JAVAGeneralPath.ClosePath()
            }));
            vg[2].translate(100, 0);
            System.err.println("class org.freehep.graphicsio.java.JAVAGraphics2D: setStroke(Stroke) not implemented.");
            vg[2].draw(new JAVAGeneralPath(1, new JAVAGeneralPath.PathElement[] {
                new JAVAGeneralPath.MoveTo(2.4169922f, -3.8085938f),
                new JAVAGeneralPath.QuadTo(8.496094f, -4.0283203f, 11.1328125f, -5.419922f),
                new JAVAGeneralPath.QuadTo(15.600586f, -7.763672f, 15.600586f, -14.355469f),
                new JAVAGeneralPath.LineTo(15.600586f, -86.93848f),
                new JAVAGeneralPath.QuadTo(15.600586f, -93.53027f, 11.425781f, -95.80078f),
                new JAVAGeneralPath.QuadTo(8.935547f, -97.19238f, 2.4169922f, -97.55859f),
                new JAVAGeneralPath.LineTo(2.4169922f, -101.36719f),
                new JAVAGeneralPath.LineTo(48.779297f, -101.36719f),
                new JAVAGeneralPath.QuadTo(62.182617f, -101.36719f, 71.04492f, -98.291016f),
                new JAVAGeneralPath.QuadTo(87.74414f, -92.50488f, 87.74414f, -77.197266f),
                new JAVAGeneralPath.QuadTo(87.74414f, -67.89551f, 80.96924f, -62.438965f),
                new JAVAGeneralPath.QuadTo(74.194336f, -56.98242f, 66.28418f, -55.51758f),
                new JAVAGeneralPath.LineTo(66.28418f, -54.125977f),
                new JAVAGeneralPath.QuadTo(74.63379f, -52.51465f, 80.78613f, -48.706055f),
                new JAVAGeneralPath.QuadTo(92.79785f, -41.23535f, 92.79785f, -27.905273f),
                new JAVAGeneralPath.QuadTo(92.79785f, -15.454102f, 81.29883f, -7.727051f),
                new JAVAGeneralPath.QuadTo(69.799805f, 0.0f, 50.683594f, 0.0f),
                new JAVAGeneralPath.LineTo(2.4169922f, 0.0f),
                new JAVAGeneralPath.ClosePath(),
                new JAVAGeneralPath.MoveTo(39.55078f, -55.88379f),
                new JAVAGeneralPath.QuadTo(53.466797f, -55.88379f, 58.22754f, -60.424805f),
                new JAVAGeneralPath.QuadTo(62.98828f, -64.96582f, 62.98828f, -76.538086f),
                new JAVAGeneralPath.QuadTo(62.98828f, -85.10742f, 59.87549f, -90.9668f),
                new JAVAGeneralPath.QuadTo(56.762695f, -96.82617f, 47.90039f, -96.82617f),
                new JAVAGeneralPath.QuadTo(43.21289f, -96.82617f, 41.381836f, -95.251465f),
                new JAVAGeneralPath.QuadTo(39.55078f, -93.67676f, 39.55078f, -89.575195f),
                new JAVAGeneralPath.LineTo(39.55078f, -55.88379f),
                new JAVAGeneralPath.ClosePath(),
                new JAVAGeneralPath.MoveTo(39.55078f, -13.842773f),
                new JAVAGeneralPath.QuadTo(39.624023f, -9.887695f, 40.722656f, -8.056641f),
                new JAVAGeneralPath.QuadTo(42.55371f, -4.8339844f, 47.753906f, -4.8339844f),
                new JAVAGeneralPath.QuadTo(58.374023f, -4.8339844f, 62.65869f, -10.620117f),
                new JAVAGeneralPath.QuadTo(66.94336f, -16.40625f, 66.94336f, -27.09961f),
                new JAVAGeneralPath.QuadTo(66.94336f, -43.066406f, 57.495117f, -48.339844f),
                new JAVAGeneralPath.QuadTo(51.782227f, -51.5625f, 39.55078f, -51.342773f),
                new JAVAGeneralPath.LineTo(39.55078f, -13.842773f),
                new JAVAGeneralPath.ClosePath()
            }));
            vg[2].translate(100, 0);
            System.err.println("class org.freehep.graphicsio.java.JAVAGraphics2D: setStroke(Stroke) not implemented.");
            vg[2].draw(new JAVAGeneralPath(1, new JAVAGeneralPath.PathElement[] {
                new JAVAGeneralPath.MoveTo(2.4169922f, -3.8085938f),
                new JAVAGeneralPath.QuadTo(8.496094f, -4.0283203f, 11.1328125f, -5.419922f),
                new JAVAGeneralPath.QuadTo(15.600586f, -7.763672f, 15.600586f, -14.355469f),
                new JAVAGeneralPath.LineTo(15.600586f, -86.93848f),
                new JAVAGeneralPath.QuadTo(15.600586f, -93.53027f, 11.425781f, -95.80078f),
                new JAVAGeneralPath.QuadTo(8.935547f, -97.19238f, 2.4169922f, -97.55859f),
                new JAVAGeneralPath.LineTo(2.4169922f, -101.36719f),
                new JAVAGeneralPath.LineTo(48.779297f, -101.36719f),
                new JAVAGeneralPath.QuadTo(62.182617f, -101.36719f, 71.04492f, -98.291016f),
                new JAVAGeneralPath.QuadTo(87.74414f, -92.50488f, 87.74414f, -77.197266f),
                new JAVAGeneralPath.QuadTo(87.74414f, -67.89551f, 80.96924f, -62.438965f),
                new JAVAGeneralPath.QuadTo(74.194336f, -56.98242f, 66.28418f, -55.51758f),
                new JAVAGeneralPath.LineTo(66.28418f, -54.125977f),
                new JAVAGeneralPath.QuadTo(74.63379f, -52.51465f, 80.78613f, -48.706055f),
                new JAVAGeneralPath.QuadTo(92.79785f, -41.23535f, 92.79785f, -27.905273f),
                new JAVAGeneralPath.QuadTo(92.79785f, -15.454102f, 81.29883f, -7.727051f),
                new JAVAGeneralPath.QuadTo(69.799805f, 0.0f, 50.683594f, 0.0f),
                new JAVAGeneralPath.LineTo(2.4169922f, 0.0f),
                new JAVAGeneralPath.ClosePath(),
                new JAVAGeneralPath.MoveTo(39.55078f, -55.88379f),
                new JAVAGeneralPath.QuadTo(53.466797f, -55.88379f, 58.22754f, -60.424805f),
                new JAVAGeneralPath.QuadTo(62.98828f, -64.96582f, 62.98828f, -76.538086f),
                new JAVAGeneralPath.QuadTo(62.98828f, -85.10742f, 59.87549f, -90.9668f),
                new JAVAGeneralPath.QuadTo(56.762695f, -96.82617f, 47.90039f, -96.82617f),
                new JAVAGeneralPath.QuadTo(43.21289f, -96.82617f, 41.381836f, -95.251465f),
                new JAVAGeneralPath.QuadTo(39.55078f, -93.67676f, 39.55078f, -89.575195f),
                new JAVAGeneralPath.LineTo(39.55078f, -55.88379f),
                new JAVAGeneralPath.ClosePath(),
                new JAVAGeneralPath.MoveTo(39.55078f, -13.842773f),
                new JAVAGeneralPath.QuadTo(39.624023f, -9.887695f, 40.722656f, -8.056641f),
                new JAVAGeneralPath.QuadTo(42.55371f, -4.8339844f, 47.753906f, -4.8339844f),
                new JAVAGeneralPath.QuadTo(58.374023f, -4.8339844f, 62.65869f, -10.620117f),
                new JAVAGeneralPath.QuadTo(66.94336f, -16.40625f, 66.94336f, -27.09961f),
                new JAVAGeneralPath.QuadTo(66.94336f, -43.066406f, 57.495117f, -48.339844f),
                new JAVAGeneralPath.QuadTo(51.782227f, -51.5625f, 39.55078f, -51.342773f),
                new JAVAGeneralPath.LineTo(39.55078f, -13.842773f),
                new JAVAGeneralPath.ClosePath()
            }));
            vg[2].translate(100, 0);
            System.err.println("class org.freehep.graphicsio.java.JAVAGraphics2D: setStroke(Stroke) not implemented.");
            vg[2].draw(new JAVAGeneralPath(1, new JAVAGeneralPath.PathElement[] {
                new JAVAGeneralPath.MoveTo(2.4169922f, -3.8085938f),
                new JAVAGeneralPath.QuadTo(8.496094f, -4.0283203f, 11.1328125f, -5.419922f),
                new JAVAGeneralPath.QuadTo(15.600586f, -7.763672f, 15.600586f, -14.355469f),
                new JAVAGeneralPath.LineTo(15.600586f, -86.93848f),
                new JAVAGeneralPath.QuadTo(15.600586f, -93.53027f, 11.425781f, -95.80078f),
                new JAVAGeneralPath.QuadTo(8.935547f, -97.19238f, 2.4169922f, -97.55859f),
                new JAVAGeneralPath.LineTo(2.4169922f, -101.36719f),
                new JAVAGeneralPath.LineTo(48.779297f, -101.36719f),
                new JAVAGeneralPath.QuadTo(62.182617f, -101.36719f, 71.04492f, -98.291016f),
                new JAVAGeneralPath.QuadTo(87.74414f, -92.50488f, 87.74414f, -77.197266f),
                new JAVAGeneralPath.QuadTo(87.74414f, -67.89551f, 80.96924f, -62.438965f),
                new JAVAGeneralPath.QuadTo(74.194336f, -56.98242f, 66.28418f, -55.51758f),
                new JAVAGeneralPath.LineTo(66.28418f, -54.125977f),
                new JAVAGeneralPath.QuadTo(74.63379f, -52.51465f, 80.78613f, -48.706055f),
                new JAVAGeneralPath.QuadTo(92.79785f, -41.23535f, 92.79785f, -27.905273f),
                new JAVAGeneralPath.QuadTo(92.79785f, -15.454102f, 81.29883f, -7.727051f),
                new JAVAGeneralPath.QuadTo(69.799805f, 0.0f, 50.683594f, 0.0f),
                new JAVAGeneralPath.LineTo(2.4169922f, 0.0f),
                new JAVAGeneralPath.ClosePath(),
                new JAVAGeneralPath.MoveTo(39.55078f, -55.88379f),
                new JAVAGeneralPath.QuadTo(53.466797f, -55.88379f, 58.22754f, -60.424805f),
                new JAVAGeneralPath.QuadTo(62.98828f, -64.96582f, 62.98828f, -76.538086f),
                new JAVAGeneralPath.QuadTo(62.98828f, -85.10742f, 59.87549f, -90.9668f),
                new JAVAGeneralPath.QuadTo(56.762695f, -96.82617f, 47.90039f, -96.82617f),
                new JAVAGeneralPath.QuadTo(43.21289f, -96.82617f, 41.381836f, -95.251465f),
                new JAVAGeneralPath.QuadTo(39.55078f, -93.67676f, 39.55078f, -89.575195f),
                new JAVAGeneralPath.LineTo(39.55078f, -55.88379f),
                new JAVAGeneralPath.ClosePath(),
                new JAVAGeneralPath.MoveTo(39.55078f, -13.842773f),
                new JAVAGeneralPath.QuadTo(39.624023f, -9.887695f, 40.722656f, -8.056641f),
                new JAVAGeneralPath.QuadTo(42.55371f, -4.8339844f, 47.753906f, -4.8339844f),
                new JAVAGeneralPath.QuadTo(58.374023f, -4.8339844f, 62.65869f, -10.620117f),
                new JAVAGeneralPath.QuadTo(66.94336f, -16.40625f, 66.94336f, -27.09961f),
                new JAVAGeneralPath.QuadTo(66.94336f, -43.066406f, 57.495117f, -48.339844f),
                new JAVAGeneralPath.QuadTo(51.782227f, -51.5625f, 39.55078f, -51.342773f),
                new JAVAGeneralPath.LineTo(39.55078f, -13.842773f),
                new JAVAGeneralPath.ClosePath()
            }));
            Paint0s1.paint(vg);
        } // paint
    } // class Paint0s0

    private static class Paint0s1 {
        public static void paint(VectorGraphics[] vg) {
            vg[2].translate(100, 0);
            vg[1].dispose();
        } // paint
    } // class Paint0s1

    private VectorGraphics vg[] = new VectorGraphics[3];

    public static void main(String[] args) throws Exception {
        new TestCustomStrokes(args).runTest(600, 600);
    }
} // class
