// AUTOMATICALLY GENERATED by FreeHEP JAVAGraphics2D

package org.freehep.graphicsio.java.test;

import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;

import org.freehep.graphics2d.VectorGraphics;
import org.freehep.graphicsio.test.TestingPanel;

public class TestHTML extends TestingPanel {

    public TestHTML(String[] args) throws Exception {
        super(args);
        setName("TestHTML");
    } // contructor

    public void paint(Graphics g) {
        vg[0] = VectorGraphics.create(g);
        vg[0].setCreator("FreeHEP JAVAGraphics2D");
        Paint0s0.paint(vg);
    } // paint

    private static class Paint0s0 {
        public static void paint(VectorGraphics[] vg) {
            vg[0].setColor(new Color(0, 0, 0, 255));
            vg[0].setFont(new Font("Dialog", 0, 12));
            vg[1] = (VectorGraphics) vg[0].create();
            vg[1].setClip(0, 0, 600, 600);
            vg[2] = (VectorGraphics) vg[1].create();
            vg[2].setColor(new Color(204, 204, 204, 255));
            vg[2].fillRect(0, 0, 600, 600);
            vg[2].dispose();
            vg[3] = (VectorGraphics) vg[1].create();
            vg[4] = (VectorGraphics) vg[3].create(179, 5, 242, 38);
            vg[4].setColor(new Color(0, 0, 0, 255));
            vg[4].setFont(new Font("Dialog", 0, 12));
            vg[4].setColor(new Color(0, 0, 0, 255));
            vg[4].setFont(new Font("Dialog", 0, 12));
            vg[5] = (VectorGraphics) vg[4].create();
            vg[6] = (VectorGraphics) vg[5].create();
            vg[6].setColor(new Color(255, 255, 255, 255));
            vg[6].fillRect(0, 0, 242, 38);
            vg[6].setColor(new Color(0, 0, 0, 255));
            vg[6].setFont(new Font("Serif", 0, 14));
            vg[6].drawChars(new char[] { '\n', '<', 'V', 'e', 'c', 't', 'o',
                    'r' }, 1, 7, 3, 25);
            vg[6].setColor(new Color(0, 0, 0, 255));
            vg[6].setFont(new Font("Serif", 1, 12));
            vg[6]
                    .drawChars(new char[] { '\n', '<', 'V', 'e', 'c', 't', 'o',
                            'r', 'G', 'r', 'a', 'p', 'h', 'i', 'c', 's' }, 8,
                            8, 49, 17);
            vg[6].setColor(new Color(0, 0, 0, 255));
            vg[6].setFont(new Font("Serif", 0, 14));
            vg[6].drawChars(new char[] { '\n', '<', 'V', 'e', 'c', 't', 'o',
                    'r', 'G', 'r', 'a', 'p', 'h', 'i', 'c', 's', ' ', '&', ' ',
                    'A', 'd', 'a', 'p', 't', 'e', 'r' }, 16, 10, 96, 25);
            vg[6].setColor(new Color(0, 0, 0, 255));
            vg[6].setFont(new Font("Serif", 2, 12));
            vg[6].drawChars(new char[] { '\n', '<', 'V', 'e', 'c', 't', 'o',
                    'r', 'G', 'r', 'a', 'p', 'h', 'i', 'c', 's', ' ', '&', ' ',
                    'A', 'd', 'a', 'p', 't', 'e', 'r', 'C', 'a', 'r', 'd' },
                    26, 4, 159, 32);
            vg[6].setColor(new Color(0, 0, 0, 255));
            vg[6].setFont(new Font("Serif", 0, 14));
            vg[6].drawChars(new char[] { '\n', '<', 'V', 'e', 'c', 't', 'o',
                    'r', 'G', 'r', 'a', 'p', 'h', 'i', 'c', 's', ' ', '&', ' ',
                    'A', 'd', 'a', 'p', 't', 'e', 'r', 'C', 'a', 'r', 'd', ' ',
                    '=', ' ', 'e' }, 30, 4, 184, 25);
            vg[6].setColor(new Color(0, 0, 0, 255));
            vg[6].setFont(new Font("Serif", 0, 12));
            vg[6].drawChars(new char[] { '\n', '<', 'V', 'e', 'c', 't', 'o',
                    'r', 'G', 'r', 'a', 'p', 'h', 'i', 'c', 's', ' ', '&', ' ',
                    'A', 'd', 'a', 'p', 't', 'e', 'r', 'C', 'a', 'r', 'd', ' ',
                    '=', ' ', 'e', 'x' }, 34, 1, 206, 17);
            vg[6].setColor(new Color(0, 0, 0, 255));
            vg[6].setFont(new Font("Serif", 0, 12));
            vg[6].drawChars(new char[] { '\n', '<', 'V', 'e', 'c', 't', 'o',
                    'r', 'G', 'r', 'a', 'p', 'h', 'i', 'c', 's', ' ', '&', ' ',
                    'A', 'd', 'a', 'p', 't', 'e', 'r', 'C', 'a', 'r', 'd', ' ',
                    '=', ' ', 'e', 'x', '2' }, 35, 1, 211, 17);
            vg[6].setColor(new Color(0, 0, 0, 255));
            vg[6].setFont(new Font("Serif", 0, 12));
            vg[6].drawChars(new char[] { '\n', '<', 'V', 'e', 'c', 't', 'o',
                    'r', 'G', 'r', 'a', 'p', 'h', 'i', 'c', 's', ' ', '&', ' ',
                    'A', 'd', 'a', 'p', 't', 'e', 'r', 'C', 'a', 'r', 'd', ' ',
                    '=', ' ', 'e', 'x', '2', 'y' }, 36, 1, 217, 17);
            vg[6].setColor(new Color(0, 0, 0, 255));
            vg[6].setFont(new Font("Serif", 0, 12));
            vg[6].drawChars(new char[] { '\n', '<', 'V', 'e', 'c', 't', 'o',
                    'r', 'G', 'r', 'a', 'p', 'h', 'i', 'c', 's', ' ', '&', ' ',
                    'A', 'd', 'a', 'p', 't', 'e', 'r', 'C', 'a', 'r', 'd', ' ',
                    '=', ' ', 'e', 'x', '2', 'y', '3' }, 37, 1, 224, 17);
            vg[6].setColor(new Color(0, 0, 0, 255));
            vg[6].setFont(new Font("Serif", 0, 14));
            vg[6].drawChars(new char[] { '\n', '<', 'V', 'e', 'c', 't', 'o',
                    'r', 'G', 'r', 'a', 'p', 'h', 'i', 'c', 's', ' ', '&', ' ',
                    'A', 'd', 'a', 'p', 't', 'e', 'r', 'C', 'a', 'r', 'd', ' ',
                    '=', ' ', 'e', 'x', '2', 'y', '3', '>' }, 38, 1, 230, 25);
            vg[6].setColor(new Color(0, 0, 0, 255));
            vg[6].setFont(new Font("Serif", 0, 14));
            vg[6].dispose();
            vg[5].dispose();
            vg[4].dispose();
            vg[3].dispose();
            vg[1].dispose();
        } // paint
    } // class Paint0s0

    private VectorGraphics vg[] = new VectorGraphics[7];

    public static void main(String[] args) throws Exception {
        new TestHTML(args).runTest(600, 600);
    }
} // class
