// AUTOMATICALLY GENERATED by FreeHEP JAVAGraphics2D

package org.freehep.graphicsio.java.test;

import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;

import org.freehep.graphics2d.VectorGraphics;
import org.freehep.graphicsio.test.TestingPanel;

public class TestFontDerivation extends TestingPanel {

    public TestFontDerivation(String[] args) throws Exception {
        super(args);
        setName("TestFontDerivation");
    } // contructor

    public void paint(Graphics g) {
        vg[0] = VectorGraphics.create(g);
        vg[0].setCreator("FreeHEP JAVAGraphics2D");
        Paint0s0.paint(vg);
    } // paint

    private static class Paint0s0 {
        public static void paint(VectorGraphics[] vg) {
            vg[0].setColor(new Color(0, 0, 0, 255));
            vg[0].setFont(new Font("Dialog", 0, 12));
            vg[1] = (VectorGraphics) vg[0].create();
            vg[1].setClip(0, 0, 600, 600);
            vg[2] = (VectorGraphics) vg[1].create();
            vg[2].translate(300, 300);
            vg[2].setColor(new Color(255, 255, 255, 255));
            vg[2].fillRect(-300, -300, 600, 600);
            vg[2].setColor(new Color(0, 0, 0, 255));
            vg[2].setFont(new Font("Dialog", 0, 12));
            vg[2].drawString("FreeHEP", 0, 0);
            vg[2].setFont(new Font("Dialog", 0, 12));
            vg[2].drawString("FreeHEP", 0, 0);
            vg[2].setFont(new Font("Dialog", 0, 12));
            vg[2].drawString("FreeHEP", 0, 0);
            vg[2].setFont(new Font("Dialog", 0, 12));
            vg[2].drawString("FreeHEP", 0, 0);
            vg[2].setFont(new Font("Dialog", 0, 12));
            vg[2].drawString("FreeHEP", 0, 0);
            vg[2].setFont(new Font("Dialog", 0, 12));
            vg[2].drawString("FreeHEP", 0, 0);
            vg[2].setFont(new Font("Dialog", 0, 12));
            vg[2].drawString("FreeHEP", 0, 0);
            vg[2].setFont(new Font("Dialog", 0, 12));
            vg[2].drawString("FreeHEP", 0, 0);
            vg[2].setFont(new Font("Dialog", 0, 12));
            vg[2].drawString("FreeHEP", 0, 0);
            vg[2].setFont(new Font("Dialog", 0, 12));
            vg[2].drawString("FreeHEP", 0, 0);
            vg[2].setFont(new Font("Dialog", 0, 12));
            vg[2].drawString("FreeHEP", 0, 0);
            vg[2].setFont(new Font("Dialog", 0, 12));
            vg[2].drawString("FreeHEP", 0, 0);
            vg[2].setFont(new Font("Dialog", 0, 12));
            vg[2].drawString("FreeHEP", 0, 0);
            vg[2].setFont(new Font("Dialog", 0, 12));
            vg[2].drawString("FreeHEP", 0, 0);
            vg[2].setFont(new Font("Dialog", 0, 12));
            vg[2].drawString("FreeHEP", 0, 0);
            vg[2].setFont(new Font("Dialog", 0, 12));
            vg[2].drawString("FreeHEP", 0, 0);
            vg[2].setFont(new Font("Dialog", 0, 12));
            vg[2].drawString("FreeHEP", 0, 0);
            vg[2].setFont(new Font("Dialog", 0, 12));
            vg[2].drawString("FreeHEP", 0, 0);
            vg[2].setFont(new Font("Dialog", 0, 12));
            vg[2].drawString("FreeHEP", 0, 0);
            vg[2].setFont(new Font("Dialog", 0, 12));
            vg[2].drawString("FreeHEP", 0, 0);
            vg[2].setFont(new Font("Dialog", 0, 12));
            vg[2].drawString("FreeHEP", 0, 0);
            vg[2].setFont(new Font("Dialog", 0, 12));
            vg[2].drawString("FreeHEP", 0, 0);
            vg[2].setFont(new Font("Dialog", 0, 12));
            vg[2].drawString("FreeHEP", 0, 0);
            vg[2].setFont(new Font("Dialog", 0, 12));
            vg[2].drawString("FreeHEP", 0, 0);
            vg[2].setFont(new Font("Dialog", 0, 12));
            vg[2].drawString("FreeHEP", 0, 0);
            vg[2].setFont(new Font("Dialog", 0, 12));
            vg[2].drawString("FreeHEP", 0, 0);
            vg[2].setFont(new Font("Dialog", 0, 12));
            vg[2].drawString("FreeHEP", 0, 0);
            vg[2].setFont(new Font("Dialog", 0, 12));
            vg[2].drawString("FreeHEP", 0, 0);
            vg[2].setFont(new Font("Dialog", 0, 12));
            vg[2].drawString("FreeHEP", 0, 0);
            vg[2].setFont(new Font("Dialog", 0, 12));
            vg[2].drawString("FreeHEP", 0, 0);
            vg[2].setFont(new Font("Dialog", 0, 12));
            vg[2].drawString("FreeHEP", 0, 0);
            vg[2].setFont(new Font("Dialog", 0, 12));
            vg[2].drawString("FreeHEP", 0, 0);
            vg[2].setFont(new Font("Dialog", 0, 12));
            vg[2].drawString("FreeHEP", 0, 0);
            vg[2].setFont(new Font("Dialog", 0, 12));
            vg[2].drawString("FreeHEP", 0, 0);
            vg[2].setFont(new Font("Dialog", 0, 12));
            vg[2].drawString("FreeHEP", 0, 0);
            vg[2].setColor(new Color(0, 0, 255, 255));
            vg[2].setFont(new Font("Dialog", 0, 12));
            vg[2].drawString("FreeHEP", 0, 0);
            vg[2].dispose();
            vg[1].dispose();
        } // paint
    } // class Paint0s0

    private VectorGraphics vg[] = new VectorGraphics[3];

    public static void main(String[] args) throws Exception {
        new TestFontDerivation(args).runTest(600, 600);
    }
} // class
